[2025-10-19T13:18:21.110+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_hdfs_spark_bash.run_spark_local manual__2025-10-19T13:17:51.711515+00:00 [queued]>
[2025-10-19T13:18:21.182+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_hdfs_spark_bash.run_spark_local manual__2025-10-19T13:17:51.711515+00:00 [queued]>
[2025-10-19T13:18:21.183+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-19T13:18:21.392+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_spark_local> on 2025-10-19 13:17:51.711515+00:00
[2025-10-19T13:18:21.402+0000] {standard_task_runner.py:60} INFO - Started process 1022 to run task
[2025-10-19T13:18:21.412+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_hdfs_spark_bash', 'run_spark_local', 'manual__2025-10-19T13:17:51.711515+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/test_hdfs_spark.py', '--cfg-path', '/tmp/tmpak1jxk3z']
[2025-10-19T13:18:21.484+0000] {standard_task_runner.py:88} INFO - Job 147: Subtask run_spark_local
[2025-10-19T13:18:21.928+0000] {task_command.py:423} INFO - Running <TaskInstance: test_hdfs_spark_bash.run_spark_local manual__2025-10-19T13:17:51.711515+00:00 [running]> on host 2ef039423968
[2025-10-19T13:18:22.159+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_hdfs_spark_bash' AIRFLOW_CTX_TASK_ID='run_spark_local' AIRFLOW_CTX_EXECUTION_DATE='2025-10-19T13:17:51.711515+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-19T13:17:51.711515+00:00'
[2025-10-19T13:18:22.165+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-19T13:18:22.174+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/hdfs_spark_test.py']
[2025-10-19T13:18:22.203+0000] {subprocess.py:86} INFO - Output:
[2025-10-19T13:18:50.208+0000] {subprocess.py:93} INFO - ðŸš€ Starting Spark HDFS Test...
[2025-10-19T13:18:50.798+0000] {subprocess.py:93} INFO - 25/10/19 13:18:50 INFO SparkContext: Running Spark version 3.5.1
[2025-10-19T13:18:50.890+0000] {subprocess.py:93} INFO - 25/10/19 13:18:50 INFO SparkContext: OS info Linux, 6.6.87.2-microsoft-standard-WSL2, amd64
[2025-10-19T13:18:50.894+0000] {subprocess.py:93} INFO - 25/10/19 13:18:50 INFO SparkContext: Java version 17.0.16
[2025-10-19T13:18:51.512+0000] {subprocess.py:93} INFO - 25/10/19 13:18:51 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-10-19T13:18:52.490+0000] {subprocess.py:93} INFO - 25/10/19 13:18:52 INFO ResourceUtils: ==============================================================
[2025-10-19T13:18:52.492+0000] {subprocess.py:93} INFO - 25/10/19 13:18:52 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-10-19T13:18:52.493+0000] {subprocess.py:93} INFO - 25/10/19 13:18:52 INFO ResourceUtils: ==============================================================
[2025-10-19T13:18:52.494+0000] {subprocess.py:93} INFO - 25/10/19 13:18:52 INFO SparkContext: Submitted application: HDFS-Test
[2025-10-19T13:18:52.598+0000] {subprocess.py:93} INFO - 25/10/19 13:18:52 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-10-19T13:18:52.687+0000] {subprocess.py:93} INFO - 25/10/19 13:18:52 INFO ResourceProfile: Limiting resource is cpu
[2025-10-19T13:18:52.713+0000] {subprocess.py:93} INFO - 25/10/19 13:18:52 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-10-19T13:18:53.209+0000] {subprocess.py:93} INFO - 25/10/19 13:18:53 INFO SecurityManager: Changing view acls to: ***
[2025-10-19T13:18:53.286+0000] {subprocess.py:93} INFO - 25/10/19 13:18:53 INFO SecurityManager: Changing modify acls to: ***
[2025-10-19T13:18:53.289+0000] {subprocess.py:93} INFO - 25/10/19 13:18:53 INFO SecurityManager: Changing view acls groups to:
[2025-10-19T13:18:53.293+0000] {subprocess.py:93} INFO - 25/10/19 13:18:53 INFO SecurityManager: Changing modify acls groups to:
[2025-10-19T13:18:53.294+0000] {subprocess.py:93} INFO - 25/10/19 13:18:53 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-10-19T13:18:56.599+0000] {subprocess.py:93} INFO - 25/10/19 13:18:56 INFO Utils: Successfully started service 'sparkDriver' on port 32833.
[2025-10-19T13:18:57.004+0000] {subprocess.py:93} INFO - 25/10/19 13:18:57 INFO SparkEnv: Registering MapOutputTracker
[2025-10-19T13:18:57.590+0000] {subprocess.py:93} INFO - 25/10/19 13:18:57 INFO SparkEnv: Registering BlockManagerMaster
[2025-10-19T13:18:57.911+0000] {subprocess.py:93} INFO - 25/10/19 13:18:57 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-10-19T13:18:57.914+0000] {subprocess.py:93} INFO - 25/10/19 13:18:57 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-10-19T13:18:58.019+0000] {subprocess.py:93} INFO - 25/10/19 13:18:57 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-10-19T13:18:58.194+0000] {subprocess.py:93} INFO - 25/10/19 13:18:58 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-a46469fe-7dd5-45b7-9ce1-77fdc93c0e36
[2025-10-19T13:18:58.400+0000] {subprocess.py:93} INFO - 25/10/19 13:18:58 INFO MemoryStore: MemoryStore started with capacity 413.9 MiB
[2025-10-19T13:18:58.592+0000] {subprocess.py:93} INFO - 25/10/19 13:18:58 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-10-19T13:18:59.793+0000] {subprocess.py:93} INFO - 25/10/19 13:18:59 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-10-19T13:19:00.399+0000] {subprocess.py:93} INFO - 25/10/19 13:19:00 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-10-19T13:19:01.693+0000] {subprocess.py:93} INFO - 25/10/19 13:19:01 INFO Executor: Starting executor ID driver on host 2ef039423968
[2025-10-19T13:19:01.694+0000] {subprocess.py:93} INFO - 25/10/19 13:19:01 INFO Executor: OS info Linux, 6.6.87.2-microsoft-standard-WSL2, amd64
[2025-10-19T13:19:01.698+0000] {subprocess.py:93} INFO - 25/10/19 13:19:01 INFO Executor: Java version 17.0.16
[2025-10-19T13:19:01.710+0000] {subprocess.py:93} INFO - 25/10/19 13:19:01 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-10-19T13:19:01.713+0000] {subprocess.py:93} INFO - 25/10/19 13:19:01 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@7dcc773f for default.
[2025-10-19T13:19:01.901+0000] {subprocess.py:93} INFO - 25/10/19 13:19:01 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 33731.
[2025-10-19T13:19:01.902+0000] {subprocess.py:93} INFO - 25/10/19 13:19:01 INFO NettyBlockTransferService: Server created on 2ef039423968:33731
[2025-10-19T13:19:01.905+0000] {subprocess.py:93} INFO - 25/10/19 13:19:01 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-10-19T13:19:01.919+0000] {subprocess.py:93} INFO - 25/10/19 13:19:01 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 2ef039423968, 33731, None)
[2025-10-19T13:19:01.994+0000] {subprocess.py:93} INFO - 25/10/19 13:19:01 INFO BlockManagerMasterEndpoint: Registering block manager 2ef039423968:33731 with 413.9 MiB RAM, BlockManagerId(driver, 2ef039423968, 33731, None)
[2025-10-19T13:19:02.006+0000] {subprocess.py:93} INFO - 25/10/19 13:19:02 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 2ef039423968, 33731, None)
[2025-10-19T13:19:02.019+0000] {subprocess.py:93} INFO - 25/10/19 13:19:02 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 2ef039423968, 33731, None)
[2025-10-19T13:19:09.548+0000] {subprocess.py:93} INFO - ðŸ“‚ Trying to read from: hdfs://192.168.1.10:9000/user/winardi/data/olist/olist_customers_dataset.csv
[2025-10-19T13:19:09.950+0000] {subprocess.py:93} INFO - 25/10/19 13:19:09 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-10-19T13:19:10.041+0000] {subprocess.py:93} INFO - 25/10/19 13:19:10 INFO SharedState: Warehouse path is 'file:/tmp/***tmpch3dlzx9/spark-warehouse'.
[2025-10-19T13:19:17.101+0000] {subprocess.py:93} INFO - 25/10/19 13:19:17 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: hdfs://192.168.1.10:9000/user/winardi/data/olist/olist_customers_dataset.csv.
[2025-10-19T13:19:17.112+0000] {subprocess.py:93} INFO - java.net.ConnectException: Call From 2ef039423968/172.18.0.6 to hadoop:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[2025-10-19T13:19:17.142+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-10-19T13:19:17.146+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-10-19T13:19:17.148+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-10-19T13:19:17.152+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-10-19T13:19:17.153+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-10-19T13:19:17.161+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:913)
[2025-10-19T13:19:17.162+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:828)
[2025-10-19T13:19:17.163+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1616)
[2025-10-19T13:19:17.164+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-10-19T13:19:17.166+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-10-19T13:19:17.167+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-10-19T13:19:17.167+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-10-19T13:19:17.169+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy35.getFileInfo(Unknown Source)
[2025-10-19T13:19:17.170+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:965)
[2025-10-19T13:19:17.171+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-10-19T13:19:17.172+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-10-19T13:19:17.173+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-10-19T13:19:17.174+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-10-19T13:19:17.175+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-10-19T13:19:17.177+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-10-19T13:19:17.177+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-10-19T13:19:17.179+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-10-19T13:19:17.181+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-10-19T13:19:17.182+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy36.getFileInfo(Unknown Source)
[2025-10-19T13:19:17.183+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1739)
[2025-10-19T13:19:17.185+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1753)
[2025-10-19T13:19:17.186+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1750)
[2025-10-19T13:19:17.187+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-10-19T13:19:17.188+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1765)
[2025-10-19T13:19:17.190+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.isDirectory(FileSystem.java:1777)
[2025-10-19T13:19:17.191+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:54)
[2025-10-19T13:19:17.199+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:366)
[2025-10-19T13:19:17.227+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2025-10-19T13:19:17.228+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2025-10-19T13:19:17.229+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-10-19T13:19:17.231+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2025-10-19T13:19:17.232+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:538)
[2025-10-19T13:19:17.234+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-10-19T13:19:17.235+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-10-19T13:19:17.245+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-10-19T13:19:17.246+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-10-19T13:19:17.247+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-10-19T13:19:17.248+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-10-19T13:19:17.249+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-10-19T13:19:17.252+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-10-19T13:19:17.253+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-10-19T13:19:17.254+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-10-19T13:19:17.255+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-10-19T13:19:17.258+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-10-19T13:19:17.259+0000] {subprocess.py:93} INFO - Caused by: java.net.ConnectException: Connection refused
[2025-10-19T13:19:17.260+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2025-10-19T13:19:17.261+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2025-10-19T13:19:17.262+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2025-10-19T13:19:17.263+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:205)
[2025-10-19T13:19:17.264+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:586)
[2025-10-19T13:19:17.265+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:711)
[2025-10-19T13:19:17.267+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:833)
[2025-10-19T13:19:17.268+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:414)
[2025-10-19T13:19:17.270+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1677)
[2025-10-19T13:19:17.273+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1502)
[2025-10-19T13:19:17.274+0000] {subprocess.py:93} INFO - 	... 40 more
[2025-10-19T13:19:19.357+0000] {subprocess.py:93} INFO - [ERROR][HDFS-Test] An error occurred while calling o33.csv.
[2025-10-19T13:19:19.358+0000] {subprocess.py:93} INFO - : java.net.ConnectException: Call From 2ef039423968/172.18.0.6 to hadoop:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[2025-10-19T13:19:19.361+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-10-19T13:19:19.373+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-10-19T13:19:19.375+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-10-19T13:19:19.377+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-10-19T13:19:19.399+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-10-19T13:19:19.400+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:913)
[2025-10-19T13:19:19.402+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:828)
[2025-10-19T13:19:19.427+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1616)
[2025-10-19T13:19:19.430+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-10-19T13:19:19.432+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-10-19T13:19:19.433+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-10-19T13:19:19.439+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-10-19T13:19:19.442+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy35.getFileInfo(Unknown Source)
[2025-10-19T13:19:19.444+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:965)
[2025-10-19T13:19:19.445+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-10-19T13:19:19.446+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-10-19T13:19:19.447+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-10-19T13:19:19.449+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-10-19T13:19:19.454+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-10-19T13:19:19.457+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-10-19T13:19:19.458+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-10-19T13:19:19.459+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-10-19T13:19:19.460+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-10-19T13:19:19.461+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy36.getFileInfo(Unknown Source)
[2025-10-19T13:19:19.463+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1739)
[2025-10-19T13:19:19.527+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1753)
[2025-10-19T13:19:19.537+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1750)
[2025-10-19T13:19:19.540+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-10-19T13:19:19.542+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1765)
[2025-10-19T13:19:19.545+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1760)
[2025-10-19T13:19:19.552+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4(DataSource.scala:756)
[2025-10-19T13:19:19.554+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4$adapted(DataSource.scala:754)
[2025-10-19T13:19:19.556+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:384)
[2025-10-19T13:19:19.560+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-10-19T13:19:19.561+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-10-19T13:19:19.564+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-10-19T13:19:19.565+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-10-19T13:19:19.567+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-10-19T13:19:19.626+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-10-19T13:19:19.627+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-10-19T13:19:19.628+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[2025-10-19T13:19:19.629+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[2025-10-19T13:19:19.630+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[2025-10-19T13:19:19.631+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[2025-10-19T13:19:19.632+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[2025-10-19T13:19:19.634+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[2025-10-19T13:19:19.635+0000] {subprocess.py:93} INFO - Caused by: java.net.ConnectException: Connection refused
[2025-10-19T13:19:19.640+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2025-10-19T13:19:19.641+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2025-10-19T13:19:19.642+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2025-10-19T13:19:19.643+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:205)
[2025-10-19T13:19:19.644+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:586)
[2025-10-19T13:19:19.645+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:711)
[2025-10-19T13:19:19.647+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:833)
[2025-10-19T13:19:19.648+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:414)
[2025-10-19T13:19:19.650+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1677)
[2025-10-19T13:19:19.652+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1502)
[2025-10-19T13:19:19.653+0000] {subprocess.py:93} INFO - 	... 37 more
[2025-10-19T13:19:19.656+0000] {subprocess.py:93} INFO - 
[2025-10-19T13:19:19.659+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-19T13:19:19.661+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/hdfs_spark_test.py", line 20, in main
[2025-10-19T13:19:19.663+0000] {subprocess.py:93} INFO -     df = spark.read.csv(hdfs_path, header=True, inferSchema=True)
[2025-10-19T13:19:19.665+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 740, in csv
[2025-10-19T13:19:19.666+0000] {subprocess.py:93} INFO -     return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
[2025-10-19T13:19:19.667+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-10-19T13:19:19.667+0000] {subprocess.py:93} INFO -     return_value = get_return_value(
[2025-10-19T13:19:19.668+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-10-19T13:19:19.670+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2025-10-19T13:19:19.671+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-10-19T13:19:19.672+0000] {subprocess.py:93} INFO -     raise Py4JJavaError(
[2025-10-19T13:19:19.673+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o33.csv.
[2025-10-19T13:19:19.674+0000] {subprocess.py:93} INFO - : java.net.ConnectException: Call From 2ef039423968/172.18.0.6 to hadoop:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[2025-10-19T13:19:19.676+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-10-19T13:19:19.677+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-10-19T13:19:19.678+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-10-19T13:19:19.679+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-10-19T13:19:19.727+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-10-19T13:19:19.728+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:913)
[2025-10-19T13:19:19.729+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:828)
[2025-10-19T13:19:19.730+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1616)
[2025-10-19T13:19:19.731+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-10-19T13:19:19.732+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-10-19T13:19:19.733+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-10-19T13:19:19.734+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-10-19T13:19:19.735+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy35.getFileInfo(Unknown Source)
[2025-10-19T13:19:19.736+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:965)
[2025-10-19T13:19:19.737+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-10-19T13:19:19.738+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-10-19T13:19:19.739+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-10-19T13:19:19.739+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-10-19T13:19:19.740+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-10-19T13:19:19.741+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-10-19T13:19:19.742+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-10-19T13:19:19.742+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-10-19T13:19:19.743+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-10-19T13:19:19.744+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy36.getFileInfo(Unknown Source)
[2025-10-19T13:19:19.746+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1739)
[2025-10-19T13:19:19.748+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1753)
[2025-10-19T13:19:19.748+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1750)
[2025-10-19T13:19:19.749+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-10-19T13:19:19.750+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1765)
[2025-10-19T13:19:19.751+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1760)
[2025-10-19T13:19:19.753+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4(DataSource.scala:756)
[2025-10-19T13:19:19.754+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4$adapted(DataSource.scala:754)
[2025-10-19T13:19:19.756+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:384)
[2025-10-19T13:19:19.757+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-10-19T13:19:19.758+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-10-19T13:19:19.759+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-10-19T13:19:19.762+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-10-19T13:19:19.763+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-10-19T13:19:19.765+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-10-19T13:19:19.766+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-10-19T13:19:19.768+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[2025-10-19T13:19:19.768+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[2025-10-19T13:19:19.769+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[2025-10-19T13:19:19.770+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[2025-10-19T13:19:19.774+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[2025-10-19T13:19:19.775+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[2025-10-19T13:19:19.777+0000] {subprocess.py:93} INFO - Caused by: java.net.ConnectException: Connection refused
[2025-10-19T13:19:19.778+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2025-10-19T13:19:19.779+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2025-10-19T13:19:19.780+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2025-10-19T13:19:19.781+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:205)
[2025-10-19T13:19:19.826+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:586)
[2025-10-19T13:19:19.828+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:711)
[2025-10-19T13:19:19.828+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:833)
[2025-10-19T13:19:19.829+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:414)
[2025-10-19T13:19:19.830+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1677)
[2025-10-19T13:19:19.832+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1502)
[2025-10-19T13:19:19.833+0000] {subprocess.py:93} INFO - 	... 37 more
[2025-10-19T13:19:19.836+0000] {subprocess.py:93} INFO - 
[2025-10-19T13:19:19.839+0000] {subprocess.py:93} INFO - 25/10/19 13:19:19 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-10-19T13:19:19.840+0000] {subprocess.py:93} INFO - 25/10/19 13:19:19 INFO SparkUI: Stopped Spark web UI at http://2ef039423968:4040
[2025-10-19T13:19:19.841+0000] {subprocess.py:93} INFO - 25/10/19 13:19:19 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-10-19T13:19:19.842+0000] {subprocess.py:93} INFO - 25/10/19 13:19:19 INFO MemoryStore: MemoryStore cleared
[2025-10-19T13:19:19.843+0000] {subprocess.py:93} INFO - 25/10/19 13:19:19 INFO BlockManager: BlockManager stopped
[2025-10-19T13:19:19.844+0000] {subprocess.py:93} INFO - 25/10/19 13:19:19 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-10-19T13:19:19.844+0000] {subprocess.py:93} INFO - 25/10/19 13:19:19 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-10-19T13:19:19.878+0000] {subprocess.py:93} INFO - 25/10/19 13:19:19 INFO SparkContext: Successfully stopped SparkContext
[2025-10-19T13:19:20.352+0000] {subprocess.py:93} INFO - ðŸ§¹ Spark session stopped.
[2025-10-19T13:19:20.555+0000] {subprocess.py:93} INFO - 25/10/19 13:19:20 INFO ShutdownHookManager: Shutdown hook called
[2025-10-19T13:19:20.583+0000] {subprocess.py:93} INFO - 25/10/19 13:19:20 INFO ShutdownHookManager: Deleting directory /tmp/spark-f9d21187-11a8-43d1-a1b5-dedae6a44d0d
[2025-10-19T13:19:20.660+0000] {subprocess.py:93} INFO - 25/10/19 13:19:20 INFO ShutdownHookManager: Deleting directory /tmp/spark-16861cab-b2ca-4090-9036-0604af885394
[2025-10-19T13:19:20.830+0000] {subprocess.py:93} INFO - 25/10/19 13:19:20 INFO ShutdownHookManager: Deleting directory /tmp/spark-16861cab-b2ca-4090-9036-0604af885394/pyspark-7453af00-69e1-4e67-aed4-4e6c4035d5a9
[2025-10-19T13:19:20.975+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-19T13:19:21.002+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-19T13:19:21.008+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=test_hdfs_spark_bash, task_id=run_spark_local, execution_date=20251019T131751, start_date=20251019T131821, end_date=20251019T131921
[2025-10-19T13:19:21.087+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 147 for task run_spark_local (Bash command failed. The command returned a non-zero exit code 1.; 1022)
[2025-10-19T13:19:21.147+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-19T13:19:21.239+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
