[2025-10-31T02:19:32.674+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt_pipeline.dbt_run scheduled__2025-10-30T00:00:00+00:00 [queued]>
[2025-10-31T02:19:32.948+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt_pipeline.dbt_run scheduled__2025-10-30T00:00:00+00:00 [queued]>
[2025-10-31T02:19:32.950+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-10-31T02:19:33.149+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_run> on 2025-10-30 00:00:00+00:00
[2025-10-31T02:19:33.179+0000] {standard_task_runner.py:60} INFO - Started process 237 to run task
[2025-10-31T02:19:33.328+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt_pipeline', 'dbt_run', 'scheduled__2025-10-30T00:00:00+00:00', '--job-id', '342', '--raw', '--subdir', 'DAGS_FOLDER/dbt_local_dag.py', '--cfg-path', '/tmp/tmp2vtxf2n_']
[2025-10-31T02:19:33.336+0000] {standard_task_runner.py:88} INFO - Job 342: Subtask dbt_run
[2025-10-31T02:19:33.940+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_dbt_pipeline.dbt_run scheduled__2025-10-30T00:00:00+00:00 [running]> on host 257bb6028ed5
[2025-10-31T02:19:35.743+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='winardi' AIRFLOW_CTX_DAG_ID='dag_dbt_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-10-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-30T00:00:00+00:00'
[2025-10-31T02:19:35.780+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T02:19:35.836+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            cd /opt/***/include/dbt/dbt_project &&             dbt run --profiles-dir /home/***/.dbt --target dev\n        ']
[2025-10-31T02:19:35.921+0000] {subprocess.py:86} INFO - Output:
[2025-10-31T02:19:51.706+0000] {subprocess.py:93} INFO - [0m02:19:51  Running with dbt=1.9.0-b2
[2025-10-31T02:19:53.136+0000] {subprocess.py:93} INFO - [0m02:19:53  Registered adapter: postgres=1.8.2
[2025-10-31T02:19:54.917+0000] {subprocess.py:93} INFO - [0m02:19:54  Unable to do partial parsing because of a version mismatch
[2025-10-31T02:20:07.162+0000] {subprocess.py:93} INFO - [0m02:20:07  Encountered an error:
[2025-10-31T02:20:07.168+0000] {subprocess.py:93} INFO - Compilation Error in test relationships_fact_transactions_ref_dim_card_holder___payment_card_id__payment_card_id (models/datamart/schema.yml)
[2025-10-31T02:20:07.171+0000] {subprocess.py:93} INFO -   macro 'dbt_macro__test_relationships' takes no keyword argument 'arguments'
[2025-10-31T02:20:13.027+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-10-31T02:20:13.622+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-10-31T02:20:13.683+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dag_dbt_pipeline, task_id=dbt_run, execution_date=20251030T000000, start_date=20251031T021932, end_date=20251031T022013
[2025-10-31T02:20:13.829+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 342 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 237)
[2025-10-31T02:20:14.626+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-31T02:20:14.843+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
