[2025-10-31T03:12:20.562+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: dag_dbt_pipeline.dbt_run manual__2025-10-31T03:11:52.421025+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
