[2025-10-19T13:09:46.547+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_hdfs_spark_bash.run_spark_local manual__2025-10-19T13:09:25.909539+00:00 [queued]>
[2025-10-19T13:09:46.713+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_hdfs_spark_bash.run_spark_local manual__2025-10-19T13:09:25.909539+00:00 [queued]>
[2025-10-19T13:09:46.721+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-19T13:09:46.874+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_spark_local> on 2025-10-19 13:09:25.909539+00:00
[2025-10-19T13:09:46.909+0000] {standard_task_runner.py:60} INFO - Started process 815 to run task
[2025-10-19T13:09:46.934+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_hdfs_spark_bash', 'run_spark_local', 'manual__2025-10-19T13:09:25.909539+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/test_hdfs_spark.py', '--cfg-path', '/tmp/tmpcre4fexr']
[2025-10-19T13:09:47.114+0000] {standard_task_runner.py:88} INFO - Job 146: Subtask run_spark_local
[2025-10-19T13:09:50.381+0000] {task_command.py:423} INFO - Running <TaskInstance: test_hdfs_spark_bash.run_spark_local manual__2025-10-19T13:09:25.909539+00:00 [running]> on host 2ef039423968
[2025-10-19T13:09:50.808+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_hdfs_spark_bash' AIRFLOW_CTX_TASK_ID='run_spark_local' AIRFLOW_CTX_EXECUTION_DATE='2025-10-19T13:09:25.909539+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-19T13:09:25.909539+00:00'
[2025-10-19T13:09:50.816+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-19T13:09:50.825+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/hdfs_spark_test.py']
[2025-10-19T13:09:50.855+0000] {subprocess.py:86} INFO - Output:
[2025-10-19T13:10:41.299+0000] {subprocess.py:93} INFO - Starting Spark HDFS Test...
[2025-10-19T13:10:42.591+0000] {subprocess.py:93} INFO - 25/10/19 13:10:42 INFO SparkContext: Running Spark version 3.5.1
[2025-10-19T13:10:42.603+0000] {subprocess.py:93} INFO - 25/10/19 13:10:42 INFO SparkContext: OS info Linux, 6.6.87.2-microsoft-standard-WSL2, amd64
[2025-10-19T13:10:42.604+0000] {subprocess.py:93} INFO - 25/10/19 13:10:42 INFO SparkContext: Java version 17.0.16
[2025-10-19T13:10:43.320+0000] {subprocess.py:93} INFO - 25/10/19 13:10:43 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-10-19T13:10:43.983+0000] {subprocess.py:93} INFO - 25/10/19 13:10:43 INFO ResourceUtils: ==============================================================
[2025-10-19T13:10:43.985+0000] {subprocess.py:93} INFO - 25/10/19 13:10:43 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-10-19T13:10:43.991+0000] {subprocess.py:93} INFO - 25/10/19 13:10:43 INFO ResourceUtils: ==============================================================
[2025-10-19T13:10:43.992+0000] {subprocess.py:93} INFO - 25/10/19 13:10:43 INFO SparkContext: Submitted application: HDFS-Test
[2025-10-19T13:10:44.122+0000] {subprocess.py:93} INFO - 25/10/19 13:10:44 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-10-19T13:10:44.185+0000] {subprocess.py:93} INFO - 25/10/19 13:10:44 INFO ResourceProfile: Limiting resource is cpu
[2025-10-19T13:10:44.188+0000] {subprocess.py:93} INFO - 25/10/19 13:10:44 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-10-19T13:10:44.501+0000] {subprocess.py:93} INFO - 25/10/19 13:10:44 INFO SecurityManager: Changing view acls to: ***
[2025-10-19T13:10:44.506+0000] {subprocess.py:93} INFO - 25/10/19 13:10:44 INFO SecurityManager: Changing modify acls to: ***
[2025-10-19T13:10:44.510+0000] {subprocess.py:93} INFO - 25/10/19 13:10:44 INFO SecurityManager: Changing view acls groups to:
[2025-10-19T13:10:44.520+0000] {subprocess.py:93} INFO - 25/10/19 13:10:44 INFO SecurityManager: Changing modify acls groups to:
[2025-10-19T13:10:44.522+0000] {subprocess.py:93} INFO - 25/10/19 13:10:44 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-10-19T13:10:46.783+0000] {subprocess.py:93} INFO - 25/10/19 13:10:46 INFO Utils: Successfully started service 'sparkDriver' on port 44957.
[2025-10-19T13:10:47.686+0000] {subprocess.py:93} INFO - 25/10/19 13:10:47 INFO SparkEnv: Registering MapOutputTracker
[2025-10-19T13:10:48.683+0000] {subprocess.py:93} INFO - 25/10/19 13:10:48 INFO SparkEnv: Registering BlockManagerMaster
[2025-10-19T13:10:48.984+0000] {subprocess.py:93} INFO - 25/10/19 13:10:48 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-10-19T13:10:49.080+0000] {subprocess.py:93} INFO - 25/10/19 13:10:48 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-10-19T13:10:49.180+0000] {subprocess.py:93} INFO - 25/10/19 13:10:49 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-10-19T13:10:49.698+0000] {subprocess.py:93} INFO - 25/10/19 13:10:49 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-feda4ce6-4f28-4999-80f4-047cc14a10d4
[2025-10-19T13:10:49.886+0000] {subprocess.py:93} INFO - 25/10/19 13:10:49 INFO MemoryStore: MemoryStore started with capacity 413.9 MiB
[2025-10-19T13:10:50.083+0000] {subprocess.py:93} INFO - 25/10/19 13:10:50 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-10-19T13:10:51.780+0000] {subprocess.py:93} INFO - 25/10/19 13:10:51 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-10-19T13:10:51.863+0000] {subprocess.py:93} INFO - 25/10/19 13:10:51 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-10-19T13:11:02.514+0000] {subprocess.py:93} INFO - 25/10/19 13:11:02 INFO Executor: Starting executor ID driver on host 2ef039423968
[2025-10-19T13:11:02.527+0000] {subprocess.py:93} INFO - 25/10/19 13:11:02 INFO Executor: OS info Linux, 6.6.87.2-microsoft-standard-WSL2, amd64
[2025-10-19T13:11:02.531+0000] {subprocess.py:93} INFO - 25/10/19 13:11:02 INFO Executor: Java version 17.0.16
[2025-10-19T13:11:02.595+0000] {subprocess.py:93} INFO - 25/10/19 13:11:02 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-10-19T13:11:02.604+0000] {subprocess.py:93} INFO - 25/10/19 13:11:02 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@7dcc773f for default.
[2025-10-19T13:11:03.244+0000] {subprocess.py:93} INFO - 25/10/19 13:11:03 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40719.
[2025-10-19T13:11:03.248+0000] {subprocess.py:93} INFO - 25/10/19 13:11:03 INFO NettyBlockTransferService: Server created on 2ef039423968:40719
[2025-10-19T13:11:03.309+0000] {subprocess.py:93} INFO - 25/10/19 13:11:03 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-10-19T13:11:03.371+0000] {subprocess.py:93} INFO - 25/10/19 13:11:03 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 2ef039423968, 40719, None)
[2025-10-19T13:11:03.421+0000] {subprocess.py:93} INFO - 25/10/19 13:11:03 INFO BlockManagerMasterEndpoint: Registering block manager 2ef039423968:40719 with 413.9 MiB RAM, BlockManagerId(driver, 2ef039423968, 40719, None)
[2025-10-19T13:11:03.473+0000] {subprocess.py:93} INFO - 25/10/19 13:11:03 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 2ef039423968, 40719, None)
[2025-10-19T13:11:03.515+0000] {subprocess.py:93} INFO - 25/10/19 13:11:03 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 2ef039423968, 40719, None)
[2025-10-19T13:11:11.343+0000] {subprocess.py:93} INFO - Trying to read from: hdfs://192.168.1.10:9000/user/winardi/data/olist/olist_customers_dataset.csv
[2025-10-19T13:11:13.521+0000] {subprocess.py:93} INFO - 25/10/19 13:11:13 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-10-19T13:11:13.723+0000] {subprocess.py:93} INFO - 25/10/19 13:11:13 INFO SharedState: Warehouse path is 'file:/tmp/***tmpuj9fune9/spark-warehouse'.
[2025-10-19T13:11:39.946+0000] {subprocess.py:93} INFO - 25/10/19 13:11:39 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: hdfs://192.168.1.10:9000/user/winardi/data/olist/olist_customers_dataset.csv.
[2025-10-19T13:11:39.969+0000] {subprocess.py:93} INFO - java.net.ConnectException: Call From 2ef039423968/172.18.0.6 to hadoop:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[2025-10-19T13:11:39.972+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-10-19T13:11:39.977+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-10-19T13:11:39.996+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-10-19T13:11:40.023+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-10-19T13:11:40.034+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-10-19T13:11:40.084+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:913)
[2025-10-19T13:11:40.112+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:828)
[2025-10-19T13:11:40.151+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1616)
[2025-10-19T13:11:40.160+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-10-19T13:11:40.176+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-10-19T13:11:40.229+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-10-19T13:11:40.279+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-10-19T13:11:40.301+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy35.getFileInfo(Unknown Source)
[2025-10-19T13:11:40.307+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:965)
[2025-10-19T13:11:40.312+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-10-19T13:11:40.338+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-10-19T13:11:40.345+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-10-19T13:11:40.351+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-10-19T13:11:40.355+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-10-19T13:11:40.358+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-10-19T13:11:40.362+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-10-19T13:11:40.369+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-10-19T13:11:40.372+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-10-19T13:11:40.375+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy36.getFileInfo(Unknown Source)
[2025-10-19T13:11:40.382+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1739)
[2025-10-19T13:11:40.391+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1753)
[2025-10-19T13:11:40.397+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1750)
[2025-10-19T13:11:40.402+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-10-19T13:11:40.422+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1765)
[2025-10-19T13:11:40.426+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.isDirectory(FileSystem.java:1777)
[2025-10-19T13:11:40.441+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:54)
[2025-10-19T13:11:40.449+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:366)
[2025-10-19T13:11:40.465+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2025-10-19T13:11:40.481+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2025-10-19T13:11:40.513+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-10-19T13:11:40.557+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2025-10-19T13:11:40.567+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:538)
[2025-10-19T13:11:40.593+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-10-19T13:11:40.600+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-10-19T13:11:40.611+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-10-19T13:11:40.617+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-10-19T13:11:40.625+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-10-19T13:11:40.632+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-10-19T13:11:40.638+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-10-19T13:11:40.640+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-10-19T13:11:40.652+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-10-19T13:11:40.655+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-10-19T13:11:40.658+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-10-19T13:11:40.663+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-10-19T13:11:40.669+0000] {subprocess.py:93} INFO - Caused by: java.net.ConnectException: Connection refused
[2025-10-19T13:11:40.673+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2025-10-19T13:11:40.679+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2025-10-19T13:11:40.691+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2025-10-19T13:11:40.696+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:205)
[2025-10-19T13:11:40.709+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:586)
[2025-10-19T13:11:40.718+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:711)
[2025-10-19T13:11:40.726+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:833)
[2025-10-19T13:11:40.733+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:414)
[2025-10-19T13:11:40.734+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1677)
[2025-10-19T13:11:40.740+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1502)
[2025-10-19T13:11:40.742+0000] {subprocess.py:93} INFO - 	... 40 more
[2025-10-19T13:11:42.993+0000] {subprocess.py:93} INFO - ERROR: An error occurred while calling o29.csv.
[2025-10-19T13:11:43.063+0000] {subprocess.py:93} INFO - : java.net.ConnectException: Call From 2ef039423968/172.18.0.6 to hadoop:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[2025-10-19T13:11:43.073+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-10-19T13:11:43.093+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-10-19T13:11:43.108+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-10-19T13:11:43.128+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-10-19T13:11:43.131+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-10-19T13:11:43.158+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:913)
[2025-10-19T13:11:43.162+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:828)
[2025-10-19T13:11:43.162+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1616)
[2025-10-19T13:11:43.163+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-10-19T13:11:43.164+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-10-19T13:11:43.164+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-10-19T13:11:43.165+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-10-19T13:11:43.166+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy35.getFileInfo(Unknown Source)
[2025-10-19T13:11:43.168+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:965)
[2025-10-19T13:11:43.169+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-10-19T13:11:43.170+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-10-19T13:11:43.171+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-10-19T13:11:43.172+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-10-19T13:11:43.172+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-10-19T13:11:43.173+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-10-19T13:11:43.174+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-10-19T13:11:43.174+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-10-19T13:11:43.175+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-10-19T13:11:43.176+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy36.getFileInfo(Unknown Source)
[2025-10-19T13:11:43.177+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1739)
[2025-10-19T13:11:43.178+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1753)
[2025-10-19T13:11:43.179+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1750)
[2025-10-19T13:11:43.179+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-10-19T13:11:43.181+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1765)
[2025-10-19T13:11:43.183+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1760)
[2025-10-19T13:11:43.185+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4(DataSource.scala:756)
[2025-10-19T13:11:43.187+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4$adapted(DataSource.scala:754)
[2025-10-19T13:11:43.188+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:384)
[2025-10-19T13:11:43.257+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-10-19T13:11:43.258+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-10-19T13:11:43.263+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-10-19T13:11:43.265+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-10-19T13:11:43.266+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-10-19T13:11:43.266+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-10-19T13:11:43.267+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-10-19T13:11:43.270+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[2025-10-19T13:11:43.273+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[2025-10-19T13:11:43.276+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[2025-10-19T13:11:43.279+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[2025-10-19T13:11:43.290+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[2025-10-19T13:11:43.293+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[2025-10-19T13:11:43.295+0000] {subprocess.py:93} INFO - Caused by: java.net.ConnectException: Connection refused
[2025-10-19T13:11:43.297+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2025-10-19T13:11:43.357+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2025-10-19T13:11:43.376+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2025-10-19T13:11:44.086+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:205)
[2025-10-19T13:11:45.157+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:586)
[2025-10-19T13:11:45.158+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:711)
[2025-10-19T13:11:45.160+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:833)
[2025-10-19T13:11:45.164+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:414)
[2025-10-19T13:11:45.172+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1677)
[2025-10-19T13:11:45.173+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1502)
[2025-10-19T13:11:45.176+0000] {subprocess.py:93} INFO - 	... 37 more
[2025-10-19T13:11:45.177+0000] {subprocess.py:93} INFO - 
[2025-10-19T13:11:45.261+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-19T13:11:45.382+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/hdfs_spark_test.py", line 20, in main
[2025-10-19T13:11:45.457+0000] {subprocess.py:93} INFO -     df = spark.read.csv(hdfs_path, header=True, inferSchema=True)
[2025-10-19T13:11:45.460+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 740, in csv
[2025-10-19T13:11:45.463+0000] {subprocess.py:93} INFO -     return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
[2025-10-19T13:11:45.463+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-10-19T13:11:45.465+0000] {subprocess.py:93} INFO -     return_value = get_return_value(
[2025-10-19T13:11:45.465+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-10-19T13:11:45.466+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2025-10-19T13:11:45.467+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-10-19T13:11:45.468+0000] {subprocess.py:93} INFO -     raise Py4JJavaError(
[2025-10-19T13:11:45.469+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o29.csv.
[2025-10-19T13:11:45.470+0000] {subprocess.py:93} INFO - : java.net.ConnectException: Call From 2ef039423968/172.18.0.6 to hadoop:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[2025-10-19T13:11:45.471+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-10-19T13:11:45.472+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-10-19T13:11:45.474+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-10-19T13:11:45.475+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-10-19T13:11:45.476+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-10-19T13:11:45.477+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:913)
[2025-10-19T13:11:45.478+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:828)
[2025-10-19T13:11:45.479+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1616)
[2025-10-19T13:11:45.480+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-10-19T13:11:45.481+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-10-19T13:11:45.481+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-10-19T13:11:45.482+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-10-19T13:11:45.483+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy35.getFileInfo(Unknown Source)
[2025-10-19T13:11:45.483+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:965)
[2025-10-19T13:11:45.484+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-10-19T13:11:45.485+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-10-19T13:11:45.486+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-10-19T13:11:45.487+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-10-19T13:11:45.490+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-10-19T13:11:45.490+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-10-19T13:11:45.491+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-10-19T13:11:45.492+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-10-19T13:11:45.493+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-10-19T13:11:45.494+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy36.getFileInfo(Unknown Source)
[2025-10-19T13:11:45.494+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1739)
[2025-10-19T13:11:45.495+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1753)
[2025-10-19T13:11:45.495+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1750)
[2025-10-19T13:11:45.557+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-10-19T13:11:45.557+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1765)
[2025-10-19T13:11:45.559+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1760)
[2025-10-19T13:11:45.559+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4(DataSource.scala:756)
[2025-10-19T13:11:45.560+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4$adapted(DataSource.scala:754)
[2025-10-19T13:11:45.562+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:384)
[2025-10-19T13:11:45.563+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-10-19T13:11:45.657+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-10-19T13:11:45.675+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-10-19T13:11:45.684+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-10-19T13:11:45.689+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-10-19T13:11:45.694+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-10-19T13:11:45.695+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-10-19T13:11:45.696+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[2025-10-19T13:11:45.699+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[2025-10-19T13:11:45.758+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[2025-10-19T13:11:45.759+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[2025-10-19T13:11:45.761+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[2025-10-19T13:11:45.762+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[2025-10-19T13:11:45.765+0000] {subprocess.py:93} INFO - Caused by: java.net.ConnectException: Connection refused
[2025-10-19T13:11:45.766+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2025-10-19T13:11:45.767+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2025-10-19T13:11:45.857+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2025-10-19T13:11:45.862+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:205)
[2025-10-19T13:11:45.863+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:586)
[2025-10-19T13:11:45.864+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:711)
[2025-10-19T13:11:45.865+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:833)
[2025-10-19T13:11:45.866+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:414)
[2025-10-19T13:11:45.867+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1677)
[2025-10-19T13:11:45.868+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1502)
[2025-10-19T13:11:45.870+0000] {subprocess.py:93} INFO - 	... 37 more
[2025-10-19T13:11:45.872+0000] {subprocess.py:93} INFO - 
[2025-10-19T13:11:45.873+0000] {subprocess.py:93} INFO - 25/10/19 13:11:43 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-10-19T13:11:45.874+0000] {subprocess.py:93} INFO - 25/10/19 13:11:43 INFO SparkUI: Stopped Spark web UI at http://2ef039423968:4040
[2025-10-19T13:11:45.876+0000] {subprocess.py:93} INFO - 25/10/19 13:11:45 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-10-19T13:11:46.163+0000] {subprocess.py:93} INFO - 25/10/19 13:11:46 INFO MemoryStore: MemoryStore cleared
[2025-10-19T13:11:46.164+0000] {subprocess.py:93} INFO - 25/10/19 13:11:46 INFO BlockManager: BlockManager stopped
[2025-10-19T13:11:46.874+0000] {subprocess.py:93} INFO - 25/10/19 13:11:46 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-10-19T13:11:46.881+0000] {subprocess.py:93} INFO - 25/10/19 13:11:46 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-10-19T13:11:47.492+0000] {subprocess.py:93} INFO - 25/10/19 13:11:47 INFO SparkContext: Successfully stopped SparkContext
[2025-10-19T13:11:48.902+0000] {subprocess.py:93} INFO - 25/10/19 13:11:48 INFO ShutdownHookManager: Shutdown hook called
[2025-10-19T13:11:48.904+0000] {subprocess.py:93} INFO - 25/10/19 13:11:48 INFO ShutdownHookManager: Deleting directory /tmp/spark-04ca4e97-db4a-49ff-bfbe-8ba07a0d15d0/pyspark-65140c2f-c383-467e-adb1-dc6e3f6ca4c8
[2025-10-19T13:11:50.583+0000] {subprocess.py:93} INFO - 25/10/19 13:11:50 INFO ShutdownHookManager: Deleting directory /tmp/spark-04ca4e97-db4a-49ff-bfbe-8ba07a0d15d0
[2025-10-19T13:11:52.158+0000] {subprocess.py:93} INFO - 25/10/19 13:11:52 INFO ShutdownHookManager: Deleting directory /tmp/spark-ecacd78a-29bd-404a-b1d3-d9f79aa23113
[2025-10-19T13:11:52.493+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-19T13:11:52.616+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-19T13:11:53.163+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=test_hdfs_spark_bash, task_id=run_spark_local, execution_date=20251019T130925, start_date=20251019T130946, end_date=20251019T131153
[2025-10-19T13:11:53.488+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 146 for task run_spark_local (Bash command failed. The command returned a non-zero exit code 1.; 815)
[2025-10-19T13:11:53.694+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-19T13:11:53.976+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
