[2025-10-24T02:42:08.692+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_validate_staging_dag.validate_and_load_staging manual__2025-10-24T02:40:18.782108+00:00 [queued]>
[2025-10-24T02:42:09.511+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_validate_staging_dag.validate_and_load_staging manual__2025-10-24T02:40:18.782108+00:00 [queued]>
[2025-10-24T02:42:09.512+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-10-24T02:42:10.231+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_and_load_staging> on 2025-10-24 02:40:18.782108+00:00
[2025-10-24T02:42:10.503+0000] {standard_task_runner.py:60} INFO - Started process 824 to run task
[2025-10-24T02:42:10.523+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'spark_validate_staging_dag', 'validate_and_load_staging', 'manual__2025-10-24T02:40:18.782108+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/etl_validate_staging_dag.py', '--cfg-path', '/tmp/tmpdaobwx5r']
[2025-10-24T02:42:10.792+0000] {standard_task_runner.py:88} INFO - Job 181: Subtask validate_and_load_staging
[2025-10-24T02:42:13.450+0000] {task_command.py:423} INFO - Running <TaskInstance: spark_validate_staging_dag.validate_and_load_staging manual__2025-10-24T02:40:18.782108+00:00 [running]> on host 2ef039423968
[2025-10-24T02:42:15.914+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='winardi' AIRFLOW_CTX_DAG_ID='spark_validate_staging_dag' AIRFLOW_CTX_TASK_ID='validate_and_load_staging' AIRFLOW_CTX_EXECUTION_DATE='2025-10-24T02:40:18.782108+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-24T02:40:18.782108+00:00'
[2025-10-24T02:42:18.266+0000] {base.py:83} INFO - Using connection ID 'pg_conn' for task execution.
[2025-10-24T02:44:45.370+0000] {etl_validate_staging_dag.py:47} INFO - Data loaded. Total rows: 189500
[2025-10-24T02:44:57.864+0000] {etl_validate_staging_dag.py:84} INFO - Null value check result:
[2025-10-24T02:44:57.865+0000] {etl_validate_staging_dag.py:86} INFO - transID: 189500 null values
[2025-10-24T02:44:57.867+0000] {etl_validate_staging_dag.py:86} INFO - payCardID: 0 null values
[2025-10-24T02:44:57.868+0000] {etl_validate_staging_dag.py:86} INFO - corridorID: 177001 null values
[2025-10-24T02:44:57.870+0000] {etl_validate_staging_dag.py:86} INFO - direction: 0 null values
[2025-10-24T02:44:57.871+0000] {etl_validate_staging_dag.py:86} INFO - tapInStops: 7241 null values
[2025-10-24T02:44:57.875+0000] {etl_validate_staging_dag.py:86} INFO - tapInTime: 0 null values
[2025-10-24T02:44:57.876+0000] {etl_validate_staging_dag.py:86} INFO - tapOutStops: 12369 null values
[2025-10-24T02:44:57.876+0000] {etl_validate_staging_dag.py:86} INFO - tapOutTime: 6720 null values
[2025-10-24T02:44:57.877+0000] {etl_validate_staging_dag.py:86} INFO - payAmount: 3718 null values
[2025-10-24T02:44:57.878+0000] {etl_validate_staging_dag.py:86} INFO - tapInStopsLat: 0 null values
[2025-10-24T02:44:57.878+0000] {etl_validate_staging_dag.py:86} INFO - tapInStopsLon: 0 null values
[2025-10-24T02:44:57.879+0000] {etl_validate_staging_dag.py:86} INFO - tapOutStopsLat: 6720 null values
[2025-10-24T02:44:57.880+0000] {etl_validate_staging_dag.py:86} INFO - tapOutStopsLon: 6720 null values
[2025-10-24T02:44:57.885+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl_validate_staging_dag.py", line 91, in validate_and_load_staging
    raise ValueError(f"Data validation failed! Nulls found in columns: {invalid_cols}")
ValueError: Data validation failed! Nulls found in columns: ['transID', 'corridorID', 'tapInStops', 'tapOutStops', 'tapOutTime', 'payAmount', 'tapOutStopsLat', 'tapOutStopsLon']
[2025-10-24T02:44:57.957+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_validate_staging_dag, task_id=validate_and_load_staging, execution_date=20251024T024018, start_date=20251024T024208, end_date=20251024T024457
[2025-10-24T02:44:58.014+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 181 for task validate_and_load_staging (Data validation failed! Nulls found in columns: ['transID', 'corridorID', 'tapInStops', 'tapOutStops', 'tapOutTime', 'payAmount', 'tapOutStopsLat', 'tapOutStopsLon']; 824)
[2025-10-24T02:44:58.155+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-24T02:44:58.187+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
