[2025-10-31T03:03:28.644+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt_pipeline.dbt_run manual__2025-10-31T03:03:23.222654+00:00 [queued]>
[2025-10-31T03:03:28.789+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt_pipeline.dbt_run manual__2025-10-31T03:03:23.222654+00:00 [queued]>
[2025-10-31T03:03:28.790+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-10-31T03:03:29.190+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_run> on 2025-10-31 03:03:23.222654+00:00
[2025-10-31T03:03:29.245+0000] {standard_task_runner.py:60} INFO - Started process 835 to run task
[2025-10-31T03:03:29.331+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt_pipeline', 'dbt_run', 'manual__2025-10-31T03:03:23.222654+00:00', '--job-id', '350', '--raw', '--subdir', 'DAGS_FOLDER/dbt_local_dag.py', '--cfg-path', '/tmp/tmp3w8fiv83']
[2025-10-31T03:03:29.339+0000] {standard_task_runner.py:88} INFO - Job 350: Subtask dbt_run
[2025-10-31T03:03:30.344+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_dbt_pipeline.dbt_run manual__2025-10-31T03:03:23.222654+00:00 [running]> on host 257bb6028ed5
[2025-10-31T03:03:31.704+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='winardi' AIRFLOW_CTX_DAG_ID='dag_dbt_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T03:03:23.222654+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T03:03:23.222654+00:00'
[2025-10-31T03:03:31.742+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T03:03:31.755+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            cd /opt/***/include/dbt/dbt_project &&             dbt run --profiles-dir /home/***/.dbt --target dev\n        ']
[2025-10-31T03:03:31.840+0000] {subprocess.py:86} INFO - Output:
[2025-10-31T03:03:49.492+0000] {subprocess.py:93} INFO - [0m03:03:49  Running with dbt=1.9.0-b2
[2025-10-31T03:03:54.463+0000] {subprocess.py:93} INFO - [0m03:03:54  Registered adapter: postgres=1.8.2
[2025-10-31T03:04:30.756+0000] {subprocess.py:93} INFO - [0m03:04:30  Found 5 models, 16 data tests, 1 source, 423 macros
[2025-10-31T03:04:31.098+0000] {subprocess.py:93} INFO - [0m03:04:31
[2025-10-31T03:04:31.164+0000] {subprocess.py:93} INFO - [0m03:04:31  Concurrency: 1 threads (target='dev')
[2025-10-31T03:04:31.174+0000] {subprocess.py:93} INFO - [0m03:04:31
[2025-10-31T03:04:38.181+0000] {subprocess.py:93} INFO - [0m03:04:38  1 of 5 START sql table model datamart.dim_card_holder .......................... [RUN]
[2025-10-31T03:04:46.867+0000] {subprocess.py:93} INFO - [0m03:04:46  1 of 5 OK created sql table model datamart.dim_card_holder ..................... [[32mSELECT 10000[0m in 8.39s]
[2025-10-31T03:04:47.143+0000] {subprocess.py:93} INFO - [0m03:04:47  2 of 5 START sql table model datamart.dim_corridor ............................. [RUN]
[2025-10-31T03:04:57.522+0000] {subprocess.py:93} INFO - [0m03:04:57  2 of 5 OK created sql table model datamart.dim_corridor ........................ [[32mSELECT 221[0m in 10.35s]
[2025-10-31T03:04:57.582+0000] {subprocess.py:93} INFO - [0m03:04:57  3 of 5 START sql table model datamart.dim_stop ................................. [RUN]
[2025-10-31T03:05:03.827+0000] {subprocess.py:93} INFO - [0m03:05:03  3 of 5 OK created sql table model datamart.dim_stop ............................ [[32mSELECT 5851[0m in 6.16s]
[2025-10-31T03:05:03.928+0000] {subprocess.py:93} INFO - [0m03:05:03  4 of 5 START sql table model datamart.dim_time ................................. [RUN]
[2025-10-31T03:05:11.650+0000] {subprocess.py:93} INFO - [0m03:05:11  4 of 5 OK created sql table model datamart.dim_time ............................ [[32mSELECT 27836[0m in 7.68s]
[2025-10-31T03:05:11.752+0000] {subprocess.py:93} INFO - [0m03:05:11  5 of 5 START sql incremental model datamart.fact_transactions .................. [RUN]
[2025-10-31T03:05:17.121+0000] {subprocess.py:93} INFO - [0m03:05:17  5 of 5 ERROR creating sql incremental model datamart.fact_transactions ......... [[31mERROR[0m in 5.24s]
[2025-10-31T03:05:18.226+0000] {subprocess.py:93} INFO - [0m03:05:18
[2025-10-31T03:05:18.241+0000] {subprocess.py:93} INFO - [0m03:05:18  Finished running 1 incremental model, 4 table models in 0 hours 0 minutes and 47.05 seconds (47.05s).
[2025-10-31T03:05:22.418+0000] {subprocess.py:93} INFO - [0m03:05:22
[2025-10-31T03:05:22.516+0000] {subprocess.py:93} INFO - [0m03:05:22  [31mCompleted with 1 error, 0 partial successs, and 0 warnings:[0m
[2025-10-31T03:05:22.617+0000] {subprocess.py:93} INFO - [0m03:05:22
[2025-10-31T03:05:22.623+0000] {subprocess.py:93} INFO - [0m03:05:22    Database Error in model fact_transactions (models/datamart/fact_transactions.sql)
[2025-10-31T03:05:22.625+0000] {subprocess.py:93} INFO -   column "1900-01-01" does not exist
[2025-10-31T03:05:22.716+0000] {subprocess.py:93} INFO -   LINE 38:             SELECT COALESCE(MAX(time_id_in), "1900-01-01"::t...
[2025-10-31T03:05:22.721+0000] {subprocess.py:93} INFO -                                                         ^
[2025-10-31T03:05:22.722+0000] {subprocess.py:93} INFO - [0m03:05:22
[2025-10-31T03:05:22.728+0000] {subprocess.py:93} INFO - [0m03:05:22  Done. PASS=4 WARN=0 ERROR=1 SKIP=0 TOTAL=5
[2025-10-31T03:05:33.730+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T03:05:34.575+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T03:05:35.365+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_dbt_pipeline, task_id=dbt_run, execution_date=20251031T030323, start_date=20251031T030328, end_date=20251031T030535
[2025-10-31T03:05:35.982+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 350 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 835)
[2025-10-31T03:05:36.919+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-31T03:05:38.720+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
