[2025-10-31T03:37:28.365+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt_pipeline.dbt_run manual__2025-10-31T03:35:46.169573+00:00 [queued]>
[2025-10-31T03:37:29.719+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt_pipeline.dbt_run manual__2025-10-31T03:35:46.169573+00:00 [queued]>
[2025-10-31T03:37:29.827+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-10-31T03:37:32.081+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_run> on 2025-10-31 03:35:46.169573+00:00
[2025-10-31T03:37:32.409+0000] {standard_task_runner.py:60} INFO - Started process 1277 to run task
[2025-10-31T03:37:41.206+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt_pipeline', 'dbt_run', 'manual__2025-10-31T03:35:46.169573+00:00', '--job-id', '354', '--raw', '--subdir', 'DAGS_FOLDER/dbt_local_dag.py', '--cfg-path', '/tmp/tmp3ymu9r3g']
[2025-10-31T03:37:41.333+0000] {standard_task_runner.py:88} INFO - Job 354: Subtask dbt_run
[2025-10-31T03:37:44.148+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_dbt_pipeline.dbt_run manual__2025-10-31T03:35:46.169573+00:00 [running]> on host 257bb6028ed5
[2025-10-31T03:37:55.754+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='winardi' AIRFLOW_CTX_DAG_ID='dag_dbt_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T03:35:46.169573+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T03:35:46.169573+00:00'
[2025-10-31T03:37:56.562+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T03:37:57.772+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            cd /opt/***/include/dbt/dbt_project &&             dbt run --profiles-dir /home/***/.dbt --target dev\n        ']
[2025-10-31T03:37:58.306+0000] {subprocess.py:86} INFO - Output:
[2025-10-31T03:39:00.487+0000] {subprocess.py:93} INFO - [0m03:39:00  Running with dbt=1.9.0-b2
[2025-10-31T03:39:07.799+0000] {subprocess.py:93} INFO - [0m03:39:07  Registered adapter: postgres=1.8.2
[2025-10-31T03:39:40.507+0000] {subprocess.py:93} INFO - [0m03:39:40  Found 5 models, 16 data tests, 1 source, 423 macros
[2025-10-31T03:39:40.554+0000] {subprocess.py:93} INFO - [0m03:39:40
[2025-10-31T03:39:40.557+0000] {subprocess.py:93} INFO - [0m03:39:40  Concurrency: 1 threads (target='dev')
[2025-10-31T03:39:40.567+0000] {subprocess.py:93} INFO - [0m03:39:40
[2025-10-31T03:39:44.314+0000] {subprocess.py:93} INFO - [0m03:39:44  1 of 5 START sql table model datamart.dim_card_holder .......................... [RUN]
[2025-10-31T03:40:06.991+0000] {subprocess.py:93} INFO - [0m03:40:06  1 of 5 OK created sql table model datamart.dim_card_holder ..................... [[32mSELECT 10000[0m in 22.56s]
[2025-10-31T03:40:07.026+0000] {subprocess.py:93} INFO - [0m03:40:07  2 of 5 START sql table model datamart.dim_corridor ............................. [RUN]
[2025-10-31T03:51:25.823+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-10-31T03:51:37.791+0000] {process_utils.py:131} INFO - Sending 15 to group 1277. PIDs of all processes in the group: [1285, 1286, 1296, 1277]
[2025-10-31T03:51:38.128+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1277
[2025-10-31T03:51:40.484+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-10-31T03:51:48.285+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-10-31T03:51:50.972+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1286, status='terminated', started='03:37:57') (1286) terminated with exit code None
