[2025-10-30T01:20:40.739+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_local_pipeline.dbt_run scheduled__2025-10-29T00:00:00+00:00 [queued]>
[2025-10-30T01:20:40.831+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_local_pipeline.dbt_run scheduled__2025-10-29T00:00:00+00:00 [queued]>
[2025-10-30T01:20:40.888+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-10-30T01:20:41.088+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_run> on 2025-10-29 00:00:00+00:00
[2025-10-30T01:20:41.518+0000] {standard_task_runner.py:60} INFO - Started process 73 to run task
[2025-10-30T01:20:41.536+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dbt_local_pipeline', 'dbt_run', 'scheduled__2025-10-29T00:00:00+00:00', '--job-id', '277', '--raw', '--subdir', 'DAGS_FOLDER/dbt_local_dag.py', '--cfg-path', '/tmp/tmpczvnwgw6']
[2025-10-30T01:20:41.635+0000] {standard_task_runner.py:88} INFO - Job 277: Subtask dbt_run
[2025-10-30T01:20:42.187+0000] {task_command.py:423} INFO - Running <TaskInstance: dbt_local_pipeline.dbt_run scheduled__2025-10-29T00:00:00+00:00 [running]> on host e51a0d90683d
[2025-10-30T01:20:43.324+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='winardi' AIRFLOW_CTX_DAG_ID='dbt_local_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-10-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-29T00:00:00+00:00'
[2025-10-30T01:20:43.336+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-30T01:20:43.348+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            cd /opt/***/include/dbt/dbt_project &&             dbt run --profiles-dir /home/***/.dbt --target dev\n        ']
[2025-10-30T01:20:43.704+0000] {subprocess.py:86} INFO - Output:
[2025-10-30T01:21:14.852+0000] {subprocess.py:93} INFO - [0m01:21:14  Running with dbt=1.9.0-b2
[2025-10-30T01:21:16.507+0000] {subprocess.py:93} INFO - [0m01:21:16  Registered adapter: postgres=1.8.2
[2025-10-30T01:21:17.315+0000] {subprocess.py:93} INFO - [0m01:21:17  Unable to do partial parsing because of a version mismatch
[2025-10-30T01:21:24.212+0000] {subprocess.py:93} INFO - [0m01:21:24  [[33mWARNING[0m]: Did not find matching node for patch with name 'dim_date' in the 'models' section of file 'models/datamart/schema.yml'
[2025-10-30T01:21:24.626+0000] {subprocess.py:93} INFO - [0m01:21:24  Encountered an error:
[2025-10-30T01:21:24.627+0000] {subprocess.py:93} INFO - Compilation Error in test relationships_fact_transactions_ref_dim_card_holder___payment_card_id__passenger_id (models/datamart/schema.yml)
[2025-10-30T01:21:24.628+0000] {subprocess.py:93} INFO -   macro 'dbt_macro__test_relationships' takes no keyword argument 'arguments'
[2025-10-30T01:21:29.429+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-10-30T01:21:29.497+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-10-30T01:21:29.582+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dbt_local_pipeline, task_id=dbt_run, execution_date=20251029T000000, start_date=20251030T012040, end_date=20251030T012129
[2025-10-30T01:21:29.704+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 277 for task dbt_run (Bash command failed. The command returned a non-zero exit code 2.; 73)
[2025-10-30T01:21:29.756+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-30T01:21:29.850+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
