[2025-10-19T12:56:03.761+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_hdfs_spark_bash.run_spark_local manual__2025-10-19T12:55:49.035101+00:00 [queued]>
[2025-10-19T12:56:03.866+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_hdfs_spark_bash.run_spark_local manual__2025-10-19T12:55:49.035101+00:00 [queued]>
[2025-10-19T12:56:03.874+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-19T12:56:04.064+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_spark_local> on 2025-10-19 12:55:49.035101+00:00
[2025-10-19T12:56:04.091+0000] {standard_task_runner.py:60} INFO - Started process 350 to run task
[2025-10-19T12:56:04.142+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_hdfs_spark_bash', 'run_spark_local', 'manual__2025-10-19T12:55:49.035101+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/test_hdfs_spark.py', '--cfg-path', '/tmp/tmplzkjmw2b']
[2025-10-19T12:56:04.148+0000] {standard_task_runner.py:88} INFO - Job 142: Subtask run_spark_local
[2025-10-19T12:56:04.798+0000] {task_command.py:423} INFO - Running <TaskInstance: test_hdfs_spark_bash.run_spark_local manual__2025-10-19T12:55:49.035101+00:00 [running]> on host 2ef039423968
[2025-10-19T12:56:05.071+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_hdfs_spark_bash' AIRFLOW_CTX_TASK_ID='run_spark_local' AIRFLOW_CTX_EXECUTION_DATE='2025-10-19T12:55:49.035101+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-19T12:55:49.035101+00:00'
[2025-10-19T12:56:05.075+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-19T12:56:05.079+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***//dags/hdfs_spark_test.py']
[2025-10-19T12:56:05.123+0000] {subprocess.py:86} INFO - Output:
[2025-10-19T12:56:37.097+0000] {subprocess.py:93} INFO - Starting Spark HDFS Test...
[2025-10-19T12:56:38.255+0000] {subprocess.py:93} INFO - 25/10/19 12:56:38 INFO SparkContext: Running Spark version 3.5.1
[2025-10-19T12:56:38.264+0000] {subprocess.py:93} INFO - 25/10/19 12:56:38 INFO SparkContext: OS info Linux, 6.6.87.2-microsoft-standard-WSL2, amd64
[2025-10-19T12:56:38.266+0000] {subprocess.py:93} INFO - 25/10/19 12:56:38 INFO SparkContext: Java version 17.0.16
[2025-10-19T12:56:38.707+0000] {subprocess.py:93} INFO - 25/10/19 12:56:38 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-10-19T12:56:39.344+0000] {subprocess.py:93} INFO - 25/10/19 12:56:39 INFO ResourceUtils: ==============================================================
[2025-10-19T12:56:39.385+0000] {subprocess.py:93} INFO - 25/10/19 12:56:39 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-10-19T12:56:39.386+0000] {subprocess.py:93} INFO - 25/10/19 12:56:39 INFO ResourceUtils: ==============================================================
[2025-10-19T12:56:39.388+0000] {subprocess.py:93} INFO - 25/10/19 12:56:39 INFO SparkContext: Submitted application: HDFS-Test
[2025-10-19T12:56:39.600+0000] {subprocess.py:93} INFO - 25/10/19 12:56:39 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-10-19T12:56:39.630+0000] {subprocess.py:93} INFO - 25/10/19 12:56:39 INFO ResourceProfile: Limiting resource is cpu
[2025-10-19T12:56:39.708+0000] {subprocess.py:93} INFO - 25/10/19 12:56:39 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-10-19T12:56:40.444+0000] {subprocess.py:93} INFO - 25/10/19 12:56:40 INFO SecurityManager: Changing view acls to: ***
[2025-10-19T12:56:40.457+0000] {subprocess.py:93} INFO - 25/10/19 12:56:40 INFO SecurityManager: Changing modify acls to: ***
[2025-10-19T12:56:40.460+0000] {subprocess.py:93} INFO - 25/10/19 12:56:40 INFO SecurityManager: Changing view acls groups to:
[2025-10-19T12:56:40.464+0000] {subprocess.py:93} INFO - 25/10/19 12:56:40 INFO SecurityManager: Changing modify acls groups to:
[2025-10-19T12:56:40.472+0000] {subprocess.py:93} INFO - 25/10/19 12:56:40 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-10-19T12:56:45.934+0000] {subprocess.py:93} INFO - 25/10/19 12:56:45 INFO Utils: Successfully started service 'sparkDriver' on port 36849.
[2025-10-19T12:56:46.573+0000] {subprocess.py:93} INFO - 25/10/19 12:56:46 INFO SparkEnv: Registering MapOutputTracker
[2025-10-19T12:56:46.855+0000] {subprocess.py:93} INFO - 25/10/19 12:56:46 INFO SparkEnv: Registering BlockManagerMaster
[2025-10-19T12:56:46.948+0000] {subprocess.py:93} INFO - 25/10/19 12:56:46 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-10-19T12:56:46.951+0000] {subprocess.py:93} INFO - 25/10/19 12:56:46 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-10-19T12:56:46.961+0000] {subprocess.py:93} INFO - 25/10/19 12:56:46 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-10-19T12:56:47.064+0000] {subprocess.py:93} INFO - 25/10/19 12:56:47 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-35a247c9-0213-42fd-8382-ac849c31d14c
[2025-10-19T12:56:47.128+0000] {subprocess.py:93} INFO - 25/10/19 12:56:47 INFO MemoryStore: MemoryStore started with capacity 413.9 MiB
[2025-10-19T12:56:47.172+0000] {subprocess.py:93} INFO - 25/10/19 12:56:47 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-10-19T12:56:47.873+0000] {subprocess.py:93} INFO - 25/10/19 12:56:47 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-10-19T12:56:48.433+0000] {subprocess.py:93} INFO - 25/10/19 12:56:48 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-10-19T12:56:49.979+0000] {subprocess.py:93} INFO - 25/10/19 12:56:49 INFO Executor: Starting executor ID driver on host 2ef039423968
[2025-10-19T12:56:50.015+0000] {subprocess.py:93} INFO - 25/10/19 12:56:49 INFO Executor: OS info Linux, 6.6.87.2-microsoft-standard-WSL2, amd64
[2025-10-19T12:56:50.054+0000] {subprocess.py:93} INFO - 25/10/19 12:56:49 INFO Executor: Java version 17.0.16
[2025-10-19T12:56:50.063+0000] {subprocess.py:93} INFO - 25/10/19 12:56:50 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-10-19T12:56:50.073+0000] {subprocess.py:93} INFO - 25/10/19 12:56:50 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@7dcc773f for default.
[2025-10-19T12:56:50.220+0000] {subprocess.py:93} INFO - 25/10/19 12:56:50 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 34583.
[2025-10-19T12:56:50.226+0000] {subprocess.py:93} INFO - 25/10/19 12:56:50 INFO NettyBlockTransferService: Server created on 2ef039423968:34583
[2025-10-19T12:56:50.234+0000] {subprocess.py:93} INFO - 25/10/19 12:56:50 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-10-19T12:56:50.307+0000] {subprocess.py:93} INFO - 25/10/19 12:56:50 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 2ef039423968, 34583, None)
[2025-10-19T12:56:50.378+0000] {subprocess.py:93} INFO - 25/10/19 12:56:50 INFO BlockManagerMasterEndpoint: Registering block manager 2ef039423968:34583 with 413.9 MiB RAM, BlockManagerId(driver, 2ef039423968, 34583, None)
[2025-10-19T12:56:50.409+0000] {subprocess.py:93} INFO - 25/10/19 12:56:50 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 2ef039423968, 34583, None)
[2025-10-19T12:56:50.421+0000] {subprocess.py:93} INFO - 25/10/19 12:56:50 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 2ef039423968, 34583, None)
[2025-10-19T12:56:54.229+0000] {subprocess.py:93} INFO - Trying to read from: hdfs://192.168.1.10:9000/user/winardi/data/olist/olist_customers_dataset.csv
[2025-10-19T12:56:54.653+0000] {subprocess.py:93} INFO - 25/10/19 12:56:54 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-10-19T12:56:54.764+0000] {subprocess.py:93} INFO - 25/10/19 12:56:54 INFO SharedState: Warehouse path is 'file:/tmp/***tmptg8vgbul/spark-warehouse'.
[2025-10-19T12:57:38.208+0000] {subprocess.py:93} INFO - 25/10/19 12:57:38 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: hdfs://192.168.1.10:9000/user/winardi/data/olist/olist_customers_dataset.csv.
[2025-10-19T12:57:38.209+0000] {subprocess.py:93} INFO - java.net.ConnectException: Call From 2ef039423968/172.18.0.6 to hadoop:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[2025-10-19T12:57:38.210+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-10-19T12:57:38.211+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-10-19T12:57:38.213+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-10-19T12:57:38.214+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-10-19T12:57:38.217+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-10-19T12:57:38.261+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:913)
[2025-10-19T12:57:38.263+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:828)
[2025-10-19T12:57:38.264+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1616)
[2025-10-19T12:57:38.265+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-10-19T12:57:38.266+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-10-19T12:57:38.267+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-10-19T12:57:38.267+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-10-19T12:57:38.272+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy35.getFileInfo(Unknown Source)
[2025-10-19T12:57:38.273+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:965)
[2025-10-19T12:57:38.274+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-10-19T12:57:38.277+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-10-19T12:57:38.280+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-10-19T12:57:38.281+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-10-19T12:57:38.282+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-10-19T12:57:38.283+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-10-19T12:57:38.285+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-10-19T12:57:38.285+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-10-19T12:57:38.287+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-10-19T12:57:38.288+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy36.getFileInfo(Unknown Source)
[2025-10-19T12:57:38.289+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1739)
[2025-10-19T12:57:38.290+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1753)
[2025-10-19T12:57:38.292+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1750)
[2025-10-19T12:57:38.293+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-10-19T12:57:38.294+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1765)
[2025-10-19T12:57:38.295+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.isDirectory(FileSystem.java:1777)
[2025-10-19T12:57:38.296+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:54)
[2025-10-19T12:57:38.296+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:366)
[2025-10-19T12:57:38.297+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2025-10-19T12:57:38.298+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2025-10-19T12:57:38.299+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-10-19T12:57:38.300+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2025-10-19T12:57:38.301+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:538)
[2025-10-19T12:57:38.301+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-10-19T12:57:38.302+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-10-19T12:57:38.303+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-10-19T12:57:38.304+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-10-19T12:57:38.305+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-10-19T12:57:38.305+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-10-19T12:57:38.362+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-10-19T12:57:38.363+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-10-19T12:57:38.363+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-10-19T12:57:38.364+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-10-19T12:57:38.364+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-10-19T12:57:38.365+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-10-19T12:57:38.366+0000] {subprocess.py:93} INFO - Caused by: java.net.ConnectException: Connection refused
[2025-10-19T12:57:38.366+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2025-10-19T12:57:38.367+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2025-10-19T12:57:38.367+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2025-10-19T12:57:38.369+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:205)
[2025-10-19T12:57:38.369+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:586)
[2025-10-19T12:57:38.370+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:711)
[2025-10-19T12:57:38.370+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:833)
[2025-10-19T12:57:38.371+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:414)
[2025-10-19T12:57:38.371+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1677)
[2025-10-19T12:57:38.372+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1502)
[2025-10-19T12:57:38.373+0000] {subprocess.py:93} INFO - 	... 40 more
[2025-10-19T12:57:41.025+0000] {subprocess.py:93} INFO - ERROR: An error occurred while calling o29.csv.
[2025-10-19T12:57:41.027+0000] {subprocess.py:93} INFO - : java.net.ConnectException: Call From 2ef039423968/172.18.0.6 to hadoop:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[2025-10-19T12:57:41.037+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-10-19T12:57:41.038+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-10-19T12:57:41.039+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-10-19T12:57:41.040+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-10-19T12:57:41.042+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-10-19T12:57:41.043+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:913)
[2025-10-19T12:57:41.044+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:828)
[2025-10-19T12:57:41.045+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1616)
[2025-10-19T12:57:41.046+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-10-19T12:57:41.047+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-10-19T12:57:41.063+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-10-19T12:57:41.076+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-10-19T12:57:41.087+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy35.getFileInfo(Unknown Source)
[2025-10-19T12:57:41.092+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:965)
[2025-10-19T12:57:41.093+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-10-19T12:57:41.170+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-10-19T12:57:41.172+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-10-19T12:57:41.175+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-10-19T12:57:41.176+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-10-19T12:57:41.182+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-10-19T12:57:41.185+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-10-19T12:57:41.187+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-10-19T12:57:41.194+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-10-19T12:57:41.196+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy36.getFileInfo(Unknown Source)
[2025-10-19T12:57:41.211+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1739)
[2025-10-19T12:57:41.213+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1753)
[2025-10-19T12:57:41.216+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1750)
[2025-10-19T12:57:41.217+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-10-19T12:57:41.218+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1765)
[2025-10-19T12:57:41.262+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1760)
[2025-10-19T12:57:41.263+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4(DataSource.scala:756)
[2025-10-19T12:57:41.264+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4$adapted(DataSource.scala:754)
[2025-10-19T12:57:41.265+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:384)
[2025-10-19T12:57:41.266+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-10-19T12:57:41.267+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-10-19T12:57:41.268+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-10-19T12:57:41.270+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-10-19T12:57:41.271+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-10-19T12:57:41.272+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-10-19T12:57:41.274+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-10-19T12:57:41.275+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[2025-10-19T12:57:41.276+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[2025-10-19T12:57:41.277+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[2025-10-19T12:57:41.278+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[2025-10-19T12:57:41.279+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[2025-10-19T12:57:41.280+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[2025-10-19T12:57:41.281+0000] {subprocess.py:93} INFO - Caused by: java.net.ConnectException: Connection refused
[2025-10-19T12:57:41.282+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2025-10-19T12:57:41.283+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2025-10-19T12:57:41.289+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2025-10-19T12:57:41.290+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:205)
[2025-10-19T12:57:41.291+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:586)
[2025-10-19T12:57:41.311+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:711)
[2025-10-19T12:57:41.314+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:833)
[2025-10-19T12:57:41.316+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:414)
[2025-10-19T12:57:41.318+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1677)
[2025-10-19T12:57:41.364+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1502)
[2025-10-19T12:57:41.366+0000] {subprocess.py:93} INFO - 	... 37 more
[2025-10-19T12:57:41.367+0000] {subprocess.py:93} INFO - 
[2025-10-19T12:57:41.369+0000] {subprocess.py:93} INFO - 25/10/19 12:57:41 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-10-19T12:57:41.371+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-19T12:57:41.372+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/hdfs_spark_test.py", line 20, in main
[2025-10-19T12:57:41.380+0000] {subprocess.py:93} INFO -     df = spark.read.csv(hdfs_path, header=True, inferSchema=True)
[2025-10-19T12:57:41.381+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 740, in csv
[2025-10-19T12:57:41.382+0000] {subprocess.py:93} INFO -     return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
[2025-10-19T12:57:41.383+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-10-19T12:57:41.385+0000] {subprocess.py:93} INFO -     return_value = get_return_value(
[2025-10-19T12:57:41.395+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-10-19T12:57:41.397+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2025-10-19T12:57:41.400+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-10-19T12:57:41.401+0000] {subprocess.py:93} INFO -     raise Py4JJavaError(
[2025-10-19T12:57:41.403+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o29.csv.
[2025-10-19T12:57:41.409+0000] {subprocess.py:93} INFO - : java.net.ConnectException: Call From 2ef039423968/172.18.0.6 to hadoop:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[2025-10-19T12:57:41.461+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-10-19T12:57:41.464+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-10-19T12:57:41.467+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-10-19T12:57:41.471+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-10-19T12:57:41.479+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-10-19T12:57:41.484+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:913)
[2025-10-19T12:57:41.487+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:828)
[2025-10-19T12:57:41.495+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1616)
[2025-10-19T12:57:41.498+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-10-19T12:57:41.500+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-10-19T12:57:41.501+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-10-19T12:57:41.502+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-10-19T12:57:41.504+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy35.getFileInfo(Unknown Source)
[2025-10-19T12:57:41.505+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:965)
[2025-10-19T12:57:41.506+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-10-19T12:57:41.507+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-10-19T12:57:41.508+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-10-19T12:57:41.510+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-10-19T12:57:41.518+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-10-19T12:57:41.519+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-10-19T12:57:41.520+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-10-19T12:57:41.521+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-10-19T12:57:41.523+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-10-19T12:57:41.524+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy36.getFileInfo(Unknown Source)
[2025-10-19T12:57:41.562+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1739)
[2025-10-19T12:57:41.563+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1753)
[2025-10-19T12:57:41.564+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1750)
[2025-10-19T12:57:41.565+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-10-19T12:57:41.566+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1765)
[2025-10-19T12:57:41.567+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1760)
[2025-10-19T12:57:41.573+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4(DataSource.scala:756)
[2025-10-19T12:57:41.576+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4$adapted(DataSource.scala:754)
[2025-10-19T12:57:41.577+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:384)
[2025-10-19T12:57:41.578+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-10-19T12:57:41.598+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-10-19T12:57:41.599+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-10-19T12:57:41.600+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-10-19T12:57:41.601+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-10-19T12:57:41.602+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-10-19T12:57:41.603+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-10-19T12:57:41.604+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[2025-10-19T12:57:41.662+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[2025-10-19T12:57:41.663+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[2025-10-19T12:57:41.665+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[2025-10-19T12:57:41.667+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[2025-10-19T12:57:41.668+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[2025-10-19T12:57:41.670+0000] {subprocess.py:93} INFO - Caused by: java.net.ConnectException: Connection refused
[2025-10-19T12:57:41.671+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2025-10-19T12:57:41.671+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2025-10-19T12:57:41.673+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2025-10-19T12:57:41.674+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:205)
[2025-10-19T12:57:41.675+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:586)
[2025-10-19T12:57:41.676+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:711)
[2025-10-19T12:57:41.677+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:833)
[2025-10-19T12:57:41.691+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:414)
[2025-10-19T12:57:41.692+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1677)
[2025-10-19T12:57:41.693+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1502)
[2025-10-19T12:57:41.694+0000] {subprocess.py:93} INFO - 	... 37 more
[2025-10-19T12:57:41.695+0000] {subprocess.py:93} INFO - 
[2025-10-19T12:57:41.697+0000] {subprocess.py:93} INFO - 25/10/19 12:57:41 INFO SparkUI: Stopped Spark web UI at http://2ef039423968:4040
[2025-10-19T12:57:41.700+0000] {subprocess.py:93} INFO - 25/10/19 12:57:41 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-10-19T12:57:41.701+0000] {subprocess.py:93} INFO - 25/10/19 12:57:41 INFO MemoryStore: MemoryStore cleared
[2025-10-19T12:57:41.703+0000] {subprocess.py:93} INFO - 25/10/19 12:57:41 INFO BlockManager: BlockManager stopped
[2025-10-19T12:57:41.705+0000] {subprocess.py:93} INFO - 25/10/19 12:57:41 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-10-19T12:57:41.706+0000] {subprocess.py:93} INFO - 25/10/19 12:57:41 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-10-19T12:57:41.879+0000] {subprocess.py:93} INFO - 25/10/19 12:57:41 INFO SparkContext: Successfully stopped SparkContext
[2025-10-19T12:57:42.865+0000] {subprocess.py:93} INFO - 25/10/19 12:57:42 INFO ShutdownHookManager: Shutdown hook called
[2025-10-19T12:57:42.874+0000] {subprocess.py:93} INFO - 25/10/19 12:57:42 INFO ShutdownHookManager: Deleting directory /tmp/spark-fc288f0c-bdd4-496d-84e5-31983da401ae/pyspark-e44ca2c8-d56b-41b2-b1cc-c09b510b85f8
[2025-10-19T12:57:43.162+0000] {subprocess.py:93} INFO - 25/10/19 12:57:43 INFO ShutdownHookManager: Deleting directory /tmp/spark-208a2f0f-1715-4a0c-87f8-22a488d1cc02
[2025-10-19T12:57:43.204+0000] {subprocess.py:93} INFO - 25/10/19 12:57:43 INFO ShutdownHookManager: Deleting directory /tmp/spark-fc288f0c-bdd4-496d-84e5-31983da401ae
[2025-10-19T12:57:43.504+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-19T12:57:43.742+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-19T12:57:44.027+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=test_hdfs_spark_bash, task_id=run_spark_local, execution_date=20251019T125549, start_date=20251019T125603, end_date=20251019T125744
[2025-10-19T12:57:44.371+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 142 for task run_spark_local (Bash command failed. The command returned a non-zero exit code 1.; 350)
[2025-10-19T12:57:44.587+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-19T12:57:44.850+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
