[2025-10-19T13:03:29.673+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_hdfs_spark_bash.run_spark_local manual__2025-10-19T13:03:21.446245+00:00 [queued]>
[2025-10-19T13:03:29.778+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_hdfs_spark_bash.run_spark_local manual__2025-10-19T13:03:21.446245+00:00 [queued]>
[2025-10-19T13:03:29.801+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-19T13:03:30.580+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_spark_local> on 2025-10-19 13:03:21.446245+00:00
[2025-10-19T13:03:30.639+0000] {standard_task_runner.py:60} INFO - Started process 638 to run task
[2025-10-19T13:03:30.683+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_hdfs_spark_bash', 'run_spark_local', 'manual__2025-10-19T13:03:21.446245+00:00', '--job-id', '145', '--raw', '--subdir', 'DAGS_FOLDER/test_hdfs_spark.py', '--cfg-path', '/tmp/tmphi79g0x8']
[2025-10-19T13:03:30.697+0000] {standard_task_runner.py:88} INFO - Job 145: Subtask run_spark_local
[2025-10-19T13:03:32.015+0000] {task_command.py:423} INFO - Running <TaskInstance: test_hdfs_spark_bash.run_spark_local manual__2025-10-19T13:03:21.446245+00:00 [running]> on host 2ef039423968
[2025-10-19T13:03:32.473+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_hdfs_spark_bash' AIRFLOW_CTX_TASK_ID='run_spark_local' AIRFLOW_CTX_EXECUTION_DATE='2025-10-19T13:03:21.446245+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-19T13:03:21.446245+00:00'
[2025-10-19T13:03:32.477+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-19T13:03:32.503+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/hdfs_spark_test.py']
[2025-10-19T13:03:32.674+0000] {subprocess.py:86} INFO - Output:
[2025-10-19T13:03:57.477+0000] {subprocess.py:93} INFO - Starting Spark HDFS Test...
[2025-10-19T13:03:58.307+0000] {subprocess.py:93} INFO - 25/10/19 13:03:58 INFO SparkContext: Running Spark version 3.5.1
[2025-10-19T13:03:58.395+0000] {subprocess.py:93} INFO - 25/10/19 13:03:58 INFO SparkContext: OS info Linux, 6.6.87.2-microsoft-standard-WSL2, amd64
[2025-10-19T13:03:58.397+0000] {subprocess.py:93} INFO - 25/10/19 13:03:58 INFO SparkContext: Java version 17.0.16
[2025-10-19T13:03:59.135+0000] {subprocess.py:93} INFO - 25/10/19 13:03:59 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-10-19T13:04:00.309+0000] {subprocess.py:93} INFO - 25/10/19 13:04:00 INFO ResourceUtils: ==============================================================
[2025-10-19T13:04:00.376+0000] {subprocess.py:93} INFO - 25/10/19 13:04:00 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-10-19T13:04:00.390+0000] {subprocess.py:93} INFO - 25/10/19 13:04:00 INFO ResourceUtils: ==============================================================
[2025-10-19T13:04:00.404+0000] {subprocess.py:93} INFO - 25/10/19 13:04:00 INFO SparkContext: Submitted application: HDFS-Test
[2025-10-19T13:04:00.680+0000] {subprocess.py:93} INFO - 25/10/19 13:04:00 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-10-19T13:04:00.809+0000] {subprocess.py:93} INFO - 25/10/19 13:04:00 INFO ResourceProfile: Limiting resource is cpu
[2025-10-19T13:04:00.876+0000] {subprocess.py:93} INFO - 25/10/19 13:04:00 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-10-19T13:04:01.395+0000] {subprocess.py:93} INFO - 25/10/19 13:04:01 INFO SecurityManager: Changing view acls to: ***
[2025-10-19T13:04:01.403+0000] {subprocess.py:93} INFO - 25/10/19 13:04:01 INFO SecurityManager: Changing modify acls to: ***
[2025-10-19T13:04:01.602+0000] {subprocess.py:93} INFO - 25/10/19 13:04:01 INFO SecurityManager: Changing view acls groups to:
[2025-10-19T13:04:01.621+0000] {subprocess.py:93} INFO - 25/10/19 13:04:01 INFO SecurityManager: Changing modify acls groups to:
[2025-10-19T13:04:01.631+0000] {subprocess.py:93} INFO - 25/10/19 13:04:01 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-10-19T13:04:03.894+0000] {subprocess.py:93} INFO - 25/10/19 13:04:03 INFO Utils: Successfully started service 'sparkDriver' on port 37501.
[2025-10-19T13:04:04.289+0000] {subprocess.py:93} INFO - 25/10/19 13:04:04 INFO SparkEnv: Registering MapOutputTracker
[2025-10-19T13:04:04.589+0000] {subprocess.py:93} INFO - 25/10/19 13:04:04 INFO SparkEnv: Registering BlockManagerMaster
[2025-10-19T13:04:04.691+0000] {subprocess.py:93} INFO - 25/10/19 13:04:04 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-10-19T13:04:04.693+0000] {subprocess.py:93} INFO - 25/10/19 13:04:04 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-10-19T13:04:04.704+0000] {subprocess.py:93} INFO - 25/10/19 13:04:04 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-10-19T13:04:05.081+0000] {subprocess.py:93} INFO - 25/10/19 13:04:05 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-3cf15b44-f3e2-41e4-9ea5-d42b8edeb6af
[2025-10-19T13:04:05.281+0000] {subprocess.py:93} INFO - 25/10/19 13:04:05 INFO MemoryStore: MemoryStore started with capacity 413.9 MiB
[2025-10-19T13:04:05.498+0000] {subprocess.py:93} INFO - 25/10/19 13:04:05 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-10-19T13:04:06.511+0000] {subprocess.py:93} INFO - 25/10/19 13:04:06 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-10-19T13:04:06.887+0000] {subprocess.py:93} INFO - 25/10/19 13:04:06 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-10-19T13:04:07.599+0000] {subprocess.py:93} INFO - 25/10/19 13:04:07 INFO Executor: Starting executor ID driver on host 2ef039423968
[2025-10-19T13:04:07.601+0000] {subprocess.py:93} INFO - 25/10/19 13:04:07 INFO Executor: OS info Linux, 6.6.87.2-microsoft-standard-WSL2, amd64
[2025-10-19T13:04:07.602+0000] {subprocess.py:93} INFO - 25/10/19 13:04:07 INFO Executor: Java version 17.0.16
[2025-10-19T13:04:07.619+0000] {subprocess.py:93} INFO - 25/10/19 13:04:07 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-10-19T13:04:07.623+0000] {subprocess.py:93} INFO - 25/10/19 13:04:07 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@32a6beeb for default.
[2025-10-19T13:04:07.781+0000] {subprocess.py:93} INFO - 25/10/19 13:04:07 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 34223.
[2025-10-19T13:04:07.804+0000] {subprocess.py:93} INFO - 25/10/19 13:04:07 INFO NettyBlockTransferService: Server created on 2ef039423968:34223
[2025-10-19T13:04:07.879+0000] {subprocess.py:93} INFO - 25/10/19 13:04:07 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-10-19T13:04:07.895+0000] {subprocess.py:93} INFO - 25/10/19 13:04:07 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 2ef039423968, 34223, None)
[2025-10-19T13:04:07.899+0000] {subprocess.py:93} INFO - 25/10/19 13:04:07 INFO BlockManagerMasterEndpoint: Registering block manager 2ef039423968:34223 with 413.9 MiB RAM, BlockManagerId(driver, 2ef039423968, 34223, None)
[2025-10-19T13:04:07.904+0000] {subprocess.py:93} INFO - 25/10/19 13:04:07 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 2ef039423968, 34223, None)
[2025-10-19T13:04:07.907+0000] {subprocess.py:93} INFO - 25/10/19 13:04:07 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 2ef039423968, 34223, None)
[2025-10-19T13:04:11.701+0000] {subprocess.py:93} INFO - Trying to read from: hdfs://192.168.1.10:9000/user/winardi/data/olist/olist_customers_dataset.csv
[2025-10-19T13:04:12.312+0000] {subprocess.py:93} INFO - 25/10/19 13:04:12 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-10-19T13:04:12.407+0000] {subprocess.py:93} INFO - 25/10/19 13:04:12 INFO SharedState: Warehouse path is 'file:/tmp/***tmp5zg0s24t/spark-warehouse'.
[2025-10-19T13:04:28.088+0000] {subprocess.py:93} INFO - 25/10/19 13:04:28 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: hdfs://192.168.1.10:9000/user/winardi/data/olist/olist_customers_dataset.csv.
[2025-10-19T13:04:28.092+0000] {subprocess.py:93} INFO - java.net.ConnectException: Call From 2ef039423968/172.18.0.6 to hadoop:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[2025-10-19T13:04:28.105+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-10-19T13:04:28.107+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-10-19T13:04:28.109+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-10-19T13:04:28.120+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-10-19T13:04:28.123+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-10-19T13:04:28.126+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:913)
[2025-10-19T13:04:28.134+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:828)
[2025-10-19T13:04:28.136+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1616)
[2025-10-19T13:04:28.185+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-10-19T13:04:28.192+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-10-19T13:04:28.193+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-10-19T13:04:28.195+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-10-19T13:04:28.205+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy35.getFileInfo(Unknown Source)
[2025-10-19T13:04:28.217+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:965)
[2025-10-19T13:04:28.223+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-10-19T13:04:28.230+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-10-19T13:04:28.233+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-10-19T13:04:28.235+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-10-19T13:04:28.236+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-10-19T13:04:28.238+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-10-19T13:04:28.239+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-10-19T13:04:28.242+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-10-19T13:04:28.244+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-10-19T13:04:28.246+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy36.getFileInfo(Unknown Source)
[2025-10-19T13:04:28.247+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1739)
[2025-10-19T13:04:28.248+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1753)
[2025-10-19T13:04:28.248+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1750)
[2025-10-19T13:04:28.281+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-10-19T13:04:28.282+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1765)
[2025-10-19T13:04:28.283+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.isDirectory(FileSystem.java:1777)
[2025-10-19T13:04:28.284+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:54)
[2025-10-19T13:04:28.285+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:366)
[2025-10-19T13:04:28.286+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2025-10-19T13:04:28.287+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2025-10-19T13:04:28.288+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-10-19T13:04:28.289+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2025-10-19T13:04:28.290+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:538)
[2025-10-19T13:04:28.290+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-10-19T13:04:28.291+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-10-19T13:04:28.291+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-10-19T13:04:28.292+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-10-19T13:04:28.293+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-10-19T13:04:28.293+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-10-19T13:04:28.294+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-10-19T13:04:28.294+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-10-19T13:04:28.295+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-10-19T13:04:28.295+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-10-19T13:04:28.296+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-10-19T13:04:28.296+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-10-19T13:04:28.297+0000] {subprocess.py:93} INFO - Caused by: java.net.ConnectException: Connection refused
[2025-10-19T13:04:28.297+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2025-10-19T13:04:28.298+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2025-10-19T13:04:28.299+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2025-10-19T13:04:28.299+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:205)
[2025-10-19T13:04:28.300+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:586)
[2025-10-19T13:04:28.300+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:711)
[2025-10-19T13:04:28.301+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:833)
[2025-10-19T13:04:28.302+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:414)
[2025-10-19T13:04:28.303+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1677)
[2025-10-19T13:04:28.304+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1502)
[2025-10-19T13:04:28.304+0000] {subprocess.py:93} INFO - 	... 40 more
[2025-10-19T13:04:31.300+0000] {subprocess.py:93} INFO - ERROR: An error occurred while calling o29.csv.
[2025-10-19T13:04:31.302+0000] {subprocess.py:93} INFO - : java.net.ConnectException: Call From 2ef039423968/172.18.0.6 to hadoop:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[2025-10-19T13:04:31.303+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-10-19T13:04:31.310+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-10-19T13:04:31.311+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-10-19T13:04:31.313+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-10-19T13:04:31.318+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-10-19T13:04:31.320+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:913)
[2025-10-19T13:04:31.323+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:828)
[2025-10-19T13:04:31.382+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1616)
[2025-10-19T13:04:31.394+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-10-19T13:04:31.397+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-10-19T13:04:31.401+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-10-19T13:04:31.414+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-10-19T13:04:31.464+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy35.getFileInfo(Unknown Source)
[2025-10-19T13:04:31.484+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:965)
[2025-10-19T13:04:31.485+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-10-19T13:04:31.487+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-10-19T13:04:31.488+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-10-19T13:04:31.489+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-10-19T13:04:31.490+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-10-19T13:04:31.491+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-10-19T13:04:31.496+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-10-19T13:04:31.497+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-10-19T13:04:31.500+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-10-19T13:04:31.510+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy36.getFileInfo(Unknown Source)
[2025-10-19T13:04:31.515+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1739)
[2025-10-19T13:04:31.520+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1753)
[2025-10-19T13:04:31.523+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1750)
[2025-10-19T13:04:31.588+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-10-19T13:04:31.612+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1765)
[2025-10-19T13:04:31.682+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1760)
[2025-10-19T13:04:31.697+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4(DataSource.scala:756)
[2025-10-19T13:04:31.700+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4$adapted(DataSource.scala:754)
[2025-10-19T13:04:31.701+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:384)
[2025-10-19T13:04:31.702+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-10-19T13:04:31.703+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-10-19T13:04:31.704+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-10-19T13:04:31.705+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-10-19T13:04:31.706+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-10-19T13:04:31.707+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-10-19T13:04:31.708+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-10-19T13:04:31.709+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[2025-10-19T13:04:31.710+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[2025-10-19T13:04:31.711+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[2025-10-19T13:04:31.711+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[2025-10-19T13:04:31.712+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[2025-10-19T13:04:31.712+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[2025-10-19T13:04:31.713+0000] {subprocess.py:93} INFO - Caused by: java.net.ConnectException: Connection refused
[2025-10-19T13:04:31.781+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2025-10-19T13:04:31.783+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2025-10-19T13:04:31.784+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2025-10-19T13:04:31.785+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:205)
[2025-10-19T13:04:31.786+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:586)
[2025-10-19T13:04:31.787+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:711)
[2025-10-19T13:04:31.788+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:833)
[2025-10-19T13:04:31.789+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:414)
[2025-10-19T13:04:31.790+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1677)
[2025-10-19T13:04:31.791+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1502)
[2025-10-19T13:04:31.792+0000] {subprocess.py:93} INFO - 	... 37 more
[2025-10-19T13:04:31.793+0000] {subprocess.py:93} INFO - 
[2025-10-19T13:04:31.794+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-19T13:04:31.795+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/hdfs_spark_test.py", line 20, in main
[2025-10-19T13:04:31.796+0000] {subprocess.py:93} INFO -     df = spark.read.csv(hdfs_path, header=True, inferSchema=True)
[2025-10-19T13:04:31.797+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 740, in csv
[2025-10-19T13:04:31.800+0000] {subprocess.py:93} INFO -     return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
[2025-10-19T13:04:31.801+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-10-19T13:04:31.802+0000] {subprocess.py:93} INFO -     return_value = get_return_value(
[2025-10-19T13:04:31.804+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-10-19T13:04:31.882+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2025-10-19T13:04:31.883+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-10-19T13:04:31.885+0000] {subprocess.py:93} INFO -     raise Py4JJavaError(
[2025-10-19T13:04:31.886+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o29.csv.
[2025-10-19T13:04:31.887+0000] {subprocess.py:93} INFO - : java.net.ConnectException: Call From 2ef039423968/172.18.0.6 to hadoop:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[2025-10-19T13:04:31.888+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-10-19T13:04:31.891+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-10-19T13:04:31.893+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-10-19T13:04:31.894+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-10-19T13:04:31.895+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-10-19T13:04:31.982+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:913)
[2025-10-19T13:04:31.993+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:828)
[2025-10-19T13:04:31.994+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1616)
[2025-10-19T13:04:31.998+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-10-19T13:04:32.000+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-10-19T13:04:32.097+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-10-19T13:04:32.098+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-10-19T13:04:32.099+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy35.getFileInfo(Unknown Source)
[2025-10-19T13:04:32.100+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:965)
[2025-10-19T13:04:32.101+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-10-19T13:04:32.102+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-10-19T13:04:32.182+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-10-19T13:04:32.200+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-10-19T13:04:32.215+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-10-19T13:04:32.217+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-10-19T13:04:32.294+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-10-19T13:04:32.299+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-10-19T13:04:32.300+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-10-19T13:04:32.307+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy36.getFileInfo(Unknown Source)
[2025-10-19T13:04:32.308+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1739)
[2025-10-19T13:04:32.309+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1753)
[2025-10-19T13:04:32.311+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1750)
[2025-10-19T13:04:32.382+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-10-19T13:04:32.383+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1765)
[2025-10-19T13:04:32.384+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1760)
[2025-10-19T13:04:32.385+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4(DataSource.scala:756)
[2025-10-19T13:04:32.389+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4$adapted(DataSource.scala:754)
[2025-10-19T13:04:32.390+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:384)
[2025-10-19T13:04:32.403+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-10-19T13:04:32.405+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-10-19T13:04:32.406+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-10-19T13:04:32.407+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-10-19T13:04:32.409+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-10-19T13:04:32.489+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-10-19T13:04:32.498+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-10-19T13:04:32.500+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[2025-10-19T13:04:32.504+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[2025-10-19T13:04:32.505+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[2025-10-19T13:04:32.506+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[2025-10-19T13:04:32.582+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[2025-10-19T13:04:32.588+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[2025-10-19T13:04:32.595+0000] {subprocess.py:93} INFO - Caused by: java.net.ConnectException: Connection refused
[2025-10-19T13:04:32.604+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2025-10-19T13:04:32.610+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2025-10-19T13:04:32.611+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2025-10-19T13:04:32.614+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:205)
[2025-10-19T13:04:32.701+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:586)
[2025-10-19T13:04:32.713+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:711)
[2025-10-19T13:04:32.789+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:833)
[2025-10-19T13:04:32.820+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:414)
[2025-10-19T13:04:32.884+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1677)
[2025-10-19T13:04:32.885+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1502)
[2025-10-19T13:04:32.887+0000] {subprocess.py:93} INFO - 	... 37 more
[2025-10-19T13:04:32.888+0000] {subprocess.py:93} INFO - 
[2025-10-19T13:04:32.889+0000] {subprocess.py:93} INFO - 25/10/19 13:04:31 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-10-19T13:04:32.890+0000] {subprocess.py:93} INFO - 25/10/19 13:04:31 INFO SparkUI: Stopped Spark web UI at http://2ef039423968:4040
[2025-10-19T13:04:32.892+0000] {subprocess.py:93} INFO - 25/10/19 13:04:31 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-10-19T13:04:32.902+0000] {subprocess.py:93} INFO - 25/10/19 13:04:32 INFO MemoryStore: MemoryStore cleared
[2025-10-19T13:04:32.903+0000] {subprocess.py:93} INFO - 25/10/19 13:04:32 INFO BlockManager: BlockManager stopped
[2025-10-19T13:04:32.905+0000] {subprocess.py:93} INFO - 25/10/19 13:04:32 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-10-19T13:04:32.909+0000] {subprocess.py:93} INFO - 25/10/19 13:04:32 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-10-19T13:04:32.910+0000] {subprocess.py:93} INFO - 25/10/19 13:04:32 INFO SparkContext: Successfully stopped SparkContext
[2025-10-19T13:04:33.117+0000] {subprocess.py:93} INFO - 25/10/19 13:04:33 INFO ShutdownHookManager: Shutdown hook called
[2025-10-19T13:04:33.155+0000] {subprocess.py:93} INFO - 25/10/19 13:04:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-aa03a25b-884e-4cad-b6e2-1d6719c1eeda
[2025-10-19T13:04:34.589+0000] {subprocess.py:93} INFO - 25/10/19 13:04:34 INFO ShutdownHookManager: Deleting directory /tmp/spark-5617c4c7-d70a-4f6e-a2f1-032a9a10c545
[2025-10-19T13:04:34.986+0000] {subprocess.py:93} INFO - 25/10/19 13:04:34 INFO ShutdownHookManager: Deleting directory /tmp/spark-aa03a25b-884e-4cad-b6e2-1d6719c1eeda/pyspark-5a5ed8e5-41cc-44cb-84d4-f652a35413bc
[2025-10-19T13:04:35.283+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-19T13:04:35.604+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-19T13:04:35.615+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=test_hdfs_spark_bash, task_id=run_spark_local, execution_date=20251019T130321, start_date=20251019T130329, end_date=20251019T130435
[2025-10-19T13:04:35.993+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 145 for task run_spark_local (Bash command failed. The command returned a non-zero exit code 1.; 638)
[2025-10-19T13:04:36.054+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-19T13:04:36.182+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
