[2025-10-31T02:44:56.953+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt_pipeline.dbt_run manual__2025-10-31T02:44:47.646693+00:00 [queued]>
[2025-10-31T02:44:56.983+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt_pipeline.dbt_run manual__2025-10-31T02:44:47.646693+00:00 [queued]>
[2025-10-31T02:44:56.984+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-10-31T02:44:57.038+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_run> on 2025-10-31 02:44:47.646693+00:00
[2025-10-31T02:44:57.059+0000] {standard_task_runner.py:60} INFO - Started process 573 to run task
[2025-10-31T02:44:57.071+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt_pipeline', 'dbt_run', 'manual__2025-10-31T02:44:47.646693+00:00', '--job-id', '346', '--raw', '--subdir', 'DAGS_FOLDER/dbt_local_dag.py', '--cfg-path', '/tmp/tmpsgx34tx4']
[2025-10-31T02:44:57.074+0000] {standard_task_runner.py:88} INFO - Job 346: Subtask dbt_run
[2025-10-31T02:44:57.372+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_dbt_pipeline.dbt_run manual__2025-10-31T02:44:47.646693+00:00 [running]> on host 257bb6028ed5
[2025-10-31T02:44:57.684+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='winardi' AIRFLOW_CTX_DAG_ID='dag_dbt_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T02:44:47.646693+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T02:44:47.646693+00:00'
[2025-10-31T02:44:57.691+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T02:44:57.696+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            cd /opt/***/include/dbt/dbt_project &&             dbt run --profiles-dir /home/***/.dbt --target dev\n        ']
[2025-10-31T02:44:57.722+0000] {subprocess.py:86} INFO - Output:
[2025-10-31T02:45:10.943+0000] {subprocess.py:93} INFO - [0m02:45:10  Running with dbt=1.9.0-b2
[2025-10-31T02:45:14.167+0000] {subprocess.py:93} INFO - [0m02:45:14  Registered adapter: postgres=1.8.2
[2025-10-31T02:45:21.774+0000] {subprocess.py:93} INFO - [0m02:45:21  Found 5 models, 16 data tests, 1 source, 423 macros
[2025-10-31T02:45:21.785+0000] {subprocess.py:93} INFO - [0m02:45:21
[2025-10-31T02:45:21.795+0000] {subprocess.py:93} INFO - [0m02:45:21  Concurrency: 1 threads (target='dev')
[2025-10-31T02:45:21.803+0000] {subprocess.py:93} INFO - [0m02:45:21
[2025-10-31T02:45:22.681+0000] {subprocess.py:93} INFO - [0m02:45:22  1 of 5 START sql table model datamart.dim_card_holder .......................... [RUN]
[2025-10-31T02:45:27.675+0000] {subprocess.py:93} INFO - [0m02:45:27  1 of 5 OK created sql table model datamart.dim_card_holder ..................... [[32mSELECT 10000[0m in 4.98s]
[2025-10-31T02:45:27.688+0000] {subprocess.py:93} INFO - [0m02:45:27  2 of 5 START sql table model datamart.dim_corridor ............................. [RUN]
[2025-10-31T02:45:28.769+0000] {subprocess.py:93} INFO - [0m02:45:28  2 of 5 OK created sql table model datamart.dim_corridor ........................ [[32mSELECT 221[0m in 1.04s]
[2025-10-31T02:45:28.782+0000] {subprocess.py:93} INFO - [0m02:45:28  3 of 5 START sql table model datamart.dim_stop ................................. [RUN]
[2025-10-31T02:45:29.604+0000] {subprocess.py:93} INFO - [0m02:45:29  3 of 5 OK created sql table model datamart.dim_stop ............................ [[32mSELECT 5851[0m in 0.82s]
[2025-10-31T02:45:29.612+0000] {subprocess.py:93} INFO - [0m02:45:29  4 of 5 START sql table model datamart.dim_time ................................. [RUN]
[2025-10-31T02:45:31.366+0000] {subprocess.py:93} INFO - [0m02:45:31  4 of 5 OK created sql table model datamart.dim_time ............................ [[32mSELECT 27836[0m in 1.75s]
[2025-10-31T02:45:31.375+0000] {subprocess.py:93} INFO - [0m02:45:31  5 of 5 START sql incremental model datamart.fact_transactions .................. [RUN]
[2025-10-31T02:45:31.701+0000] {subprocess.py:93} INFO - [0m02:45:31  5 of 5 ERROR creating sql incremental model datamart.fact_transactions ......... [[31mERROR[0m in 0.32s]
[2025-10-31T02:45:31.759+0000] {subprocess.py:93} INFO - [0m02:45:31
[2025-10-31T02:45:31.760+0000] {subprocess.py:93} INFO - [0m02:45:31  Finished running 1 incremental model, 4 table models in 0 hours 0 minutes and 9.97 seconds (9.97s).
[2025-10-31T02:45:31.871+0000] {subprocess.py:93} INFO - [0m02:45:31
[2025-10-31T02:45:31.872+0000] {subprocess.py:93} INFO - [0m02:45:31  [31mCompleted with 1 error, 0 partial successs, and 0 warnings:[0m
[2025-10-31T02:45:31.873+0000] {subprocess.py:93} INFO - [0m02:45:31
[2025-10-31T02:45:31.875+0000] {subprocess.py:93} INFO - [0m02:45:31    Database Error in model fact_transactions (models/datamart/fact_transactions.sql)
[2025-10-31T02:45:31.876+0000] {subprocess.py:93} INFO -   syntax error at or near ";"
[2025-10-31T02:45:31.877+0000] {subprocess.py:93} INFO -   LINE 86:   AND COALESCE(s.tap_in_stop_id, sl_in.stop_id) IS NOT NULL;
[2025-10-31T02:45:31.877+0000] {subprocess.py:93} INFO -                                                                       ^
[2025-10-31T02:45:31.878+0000] {subprocess.py:93} INFO - [0m02:45:31
[2025-10-31T02:45:31.884+0000] {subprocess.py:93} INFO - [0m02:45:31  Done. PASS=4 WARN=0 ERROR=1 SKIP=0 TOTAL=5
[2025-10-31T02:45:33.775+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-31T02:45:33.812+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-31T02:45:33.912+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_dbt_pipeline, task_id=dbt_run, execution_date=20251031T024447, start_date=20251031T024456, end_date=20251031T024533
[2025-10-31T02:45:34.194+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 346 for task dbt_run (Bash command failed. The command returned a non-zero exit code 1.; 573)
[2025-10-31T02:45:34.339+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-31T02:45:34.399+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
