[2025-10-31T03:26:10.171+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_dbt_pipeline.dbt_run manual__2025-10-31T03:25:38.546331+00:00 [queued]>
[2025-10-31T03:26:10.281+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_dbt_pipeline.dbt_run manual__2025-10-31T03:25:38.546331+00:00 [queued]>
[2025-10-31T03:26:10.286+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-10-31T03:26:10.410+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): dbt_run> on 2025-10-31 03:25:38.546331+00:00
[2025-10-31T03:26:10.462+0000] {standard_task_runner.py:60} INFO - Started process 1137 to run task
[2025-10-31T03:26:10.474+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dag_dbt_pipeline', 'dbt_run', 'manual__2025-10-31T03:25:38.546331+00:00', '--job-id', '353', '--raw', '--subdir', 'DAGS_FOLDER/dbt_local_dag.py', '--cfg-path', '/tmp/tmpmh10n9ik']
[2025-10-31T03:26:10.574+0000] {standard_task_runner.py:88} INFO - Job 353: Subtask dbt_run
[2025-10-31T03:26:11.043+0000] {task_command.py:423} INFO - Running <TaskInstance: dag_dbt_pipeline.dbt_run manual__2025-10-31T03:25:38.546331+00:00 [running]> on host 257bb6028ed5
[2025-10-31T03:26:12.122+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='winardi' AIRFLOW_CTX_DAG_ID='dag_dbt_pipeline' AIRFLOW_CTX_TASK_ID='dbt_run' AIRFLOW_CTX_EXECUTION_DATE='2025-10-31T03:25:38.546331+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-31T03:25:38.546331+00:00'
[2025-10-31T03:26:12.198+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-31T03:26:12.215+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            cd /opt/***/include/dbt/dbt_project &&             dbt run --profiles-dir /home/***/.dbt --target dev\n        ']
[2025-10-31T03:26:12.342+0000] {subprocess.py:86} INFO - Output:
[2025-10-31T03:26:39.412+0000] {subprocess.py:93} INFO - [0m03:26:39  Running with dbt=1.9.0-b2
[2025-10-31T03:26:44.973+0000] {subprocess.py:93} INFO - [0m03:26:44  Registered adapter: postgres=1.8.2
[2025-10-31T03:27:22.612+0000] {subprocess.py:93} INFO - [0m03:27:22  Found 5 models, 16 data tests, 1 source, 423 macros
[2025-10-31T03:27:22.845+0000] {subprocess.py:93} INFO - [0m03:27:22
[2025-10-31T03:27:22.874+0000] {subprocess.py:93} INFO - [0m03:27:22  Concurrency: 1 threads (target='dev')
[2025-10-31T03:27:22.882+0000] {subprocess.py:93} INFO - [0m03:27:22
[2025-10-31T03:27:27.425+0000] {subprocess.py:93} INFO - [0m03:27:27  1 of 5 START sql table model datamart.dim_card_holder .......................... [RUN]
[2025-10-31T03:27:35.167+0000] {subprocess.py:93} INFO - [0m03:27:35  1 of 5 OK created sql table model datamart.dim_card_holder ..................... [[32mSELECT 10000[0m in 7.72s]
[2025-10-31T03:27:35.183+0000] {subprocess.py:93} INFO - [0m03:27:35  2 of 5 START sql table model datamart.dim_corridor ............................. [RUN]
[2025-10-31T03:35:45.592+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-10-31T03:35:48.007+0000] {process_utils.py:131} INFO - Sending 15 to group 1137. PIDs of all processes in the group: [1138, 1139, 1149, 1137]
[2025-10-31T03:35:48.384+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 1137
[2025-10-31T03:35:52.503+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-10-31T03:35:55.750+0000] {subprocess.py:104} INFO - Sending SIGTERM signal to process group
[2025-10-31T03:35:57.015+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1139, status='terminated', started='03:26:11') (1139) terminated with exit code None
[2025-10-31T03:36:05.925+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1149, status='terminated', started='03:26:42') (1149) terminated with exit code None
[2025-10-31T03:36:32.185+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1138, status='terminated', started='03:26:11') (1138) terminated with exit code None
[2025-10-31T03:36:32.193+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=1137, status='terminated', exitcode=0, started='03:26:09') (1137) terminated with exit code 0
