[2025-10-11T04:06:06.454+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: my_dag.submit_job manual__2025-10-11T04:06:02.430003+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
