[2025-10-19T13:00:27.079+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_hdfs_spark_bash.run_spark_local manual__2025-10-19T13:00:18.403295+00:00 [queued]>
[2025-10-19T13:00:27.144+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_hdfs_spark_bash.run_spark_local manual__2025-10-19T13:00:18.403295+00:00 [queued]>
[2025-10-19T13:00:27.145+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-10-19T13:00:27.298+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): run_spark_local> on 2025-10-19 13:00:18.403295+00:00
[2025-10-19T13:00:27.321+0000] {standard_task_runner.py:60} INFO - Started process 502 to run task
[2025-10-19T13:00:27.356+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_hdfs_spark_bash', 'run_spark_local', 'manual__2025-10-19T13:00:18.403295+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/test_hdfs_spark.py', '--cfg-path', '/tmp/tmp7mcs0cho']
[2025-10-19T13:00:27.362+0000] {standard_task_runner.py:88} INFO - Job 143: Subtask run_spark_local
[2025-10-19T13:00:27.978+0000] {task_command.py:423} INFO - Running <TaskInstance: test_hdfs_spark_bash.run_spark_local manual__2025-10-19T13:00:18.403295+00:00 [running]> on host 2ef039423968
[2025-10-19T13:00:28.205+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_hdfs_spark_bash' AIRFLOW_CTX_TASK_ID='run_spark_local' AIRFLOW_CTX_EXECUTION_DATE='2025-10-19T13:00:18.403295+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-19T13:00:18.403295+00:00'
[2025-10-19T13:00:28.215+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-19T13:00:28.218+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/hdfs_spark_test.py']
[2025-10-19T13:00:28.268+0000] {subprocess.py:86} INFO - Output:
[2025-10-19T13:01:08.242+0000] {subprocess.py:93} INFO - Starting Spark HDFS Test...
[2025-10-19T13:01:08.490+0000] {subprocess.py:93} INFO - 25/10/19 13:01:08 INFO SparkContext: Running Spark version 3.5.1
[2025-10-19T13:01:08.520+0000] {subprocess.py:93} INFO - 25/10/19 13:01:08 INFO SparkContext: OS info Linux, 6.6.87.2-microsoft-standard-WSL2, amd64
[2025-10-19T13:01:08.521+0000] {subprocess.py:93} INFO - 25/10/19 13:01:08 INFO SparkContext: Java version 17.0.16
[2025-10-19T13:01:08.748+0000] {subprocess.py:93} INFO - 25/10/19 13:01:08 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-10-19T13:01:09.333+0000] {subprocess.py:93} INFO - 25/10/19 13:01:09 INFO ResourceUtils: ==============================================================
[2025-10-19T13:01:09.338+0000] {subprocess.py:93} INFO - 25/10/19 13:01:09 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-10-19T13:01:09.339+0000] {subprocess.py:93} INFO - 25/10/19 13:01:09 INFO ResourceUtils: ==============================================================
[2025-10-19T13:01:09.342+0000] {subprocess.py:93} INFO - 25/10/19 13:01:09 INFO SparkContext: Submitted application: HDFS-Test
[2025-10-19T13:01:09.525+0000] {subprocess.py:93} INFO - 25/10/19 13:01:09 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-10-19T13:01:09.542+0000] {subprocess.py:93} INFO - 25/10/19 13:01:09 INFO ResourceProfile: Limiting resource is cpu
[2025-10-19T13:01:09.545+0000] {subprocess.py:93} INFO - 25/10/19 13:01:09 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-10-19T13:01:09.846+0000] {subprocess.py:93} INFO - 25/10/19 13:01:09 INFO SecurityManager: Changing view acls to: ***
[2025-10-19T13:01:09.848+0000] {subprocess.py:93} INFO - 25/10/19 13:01:09 INFO SecurityManager: Changing modify acls to: ***
[2025-10-19T13:01:09.918+0000] {subprocess.py:93} INFO - 25/10/19 13:01:09 INFO SecurityManager: Changing view acls groups to:
[2025-10-19T13:01:09.919+0000] {subprocess.py:93} INFO - 25/10/19 13:01:09 INFO SecurityManager: Changing modify acls groups to:
[2025-10-19T13:01:09.944+0000] {subprocess.py:93} INFO - 25/10/19 13:01:09 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2025-10-19T13:01:12.920+0000] {subprocess.py:93} INFO - 25/10/19 13:01:12 INFO Utils: Successfully started service 'sparkDriver' on port 34731.
[2025-10-19T13:01:13.030+0000] {subprocess.py:93} INFO - 25/10/19 13:01:13 INFO SparkEnv: Registering MapOutputTracker
[2025-10-19T13:01:13.700+0000] {subprocess.py:93} INFO - 25/10/19 13:01:13 INFO SparkEnv: Registering BlockManagerMaster
[2025-10-19T13:01:14.547+0000] {subprocess.py:93} INFO - 25/10/19 13:01:14 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-10-19T13:01:14.549+0000] {subprocess.py:93} INFO - 25/10/19 13:01:14 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-10-19T13:01:14.732+0000] {subprocess.py:93} INFO - 25/10/19 13:01:14 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-10-19T13:01:16.108+0000] {subprocess.py:93} INFO - 25/10/19 13:01:16 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-df4540fc-e3b2-4a3e-a295-6efea478ef05
[2025-10-19T13:01:16.140+0000] {subprocess.py:93} INFO - 25/10/19 13:01:16 INFO MemoryStore: MemoryStore started with capacity 413.9 MiB
[2025-10-19T13:01:16.401+0000] {subprocess.py:93} INFO - 25/10/19 13:01:16 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-10-19T13:01:18.031+0000] {subprocess.py:93} INFO - 25/10/19 13:01:18 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-10-19T13:01:19.058+0000] {subprocess.py:93} INFO - 25/10/19 13:01:19 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-10-19T13:01:20.337+0000] {subprocess.py:93} INFO - 25/10/19 13:01:20 INFO Executor: Starting executor ID driver on host 2ef039423968
[2025-10-19T13:01:20.337+0000] {subprocess.py:93} INFO - 25/10/19 13:01:20 INFO Executor: OS info Linux, 6.6.87.2-microsoft-standard-WSL2, amd64
[2025-10-19T13:01:20.339+0000] {subprocess.py:93} INFO - 25/10/19 13:01:20 INFO Executor: Java version 17.0.16
[2025-10-19T13:01:20.353+0000] {subprocess.py:93} INFO - 25/10/19 13:01:20 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-10-19T13:01:20.355+0000] {subprocess.py:93} INFO - 25/10/19 13:01:20 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@7dcc773f for default.
[2025-10-19T13:01:20.654+0000] {subprocess.py:93} INFO - 25/10/19 13:01:20 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 37865.
[2025-10-19T13:01:20.655+0000] {subprocess.py:93} INFO - 25/10/19 13:01:20 INFO NettyBlockTransferService: Server created on 2ef039423968:37865
[2025-10-19T13:01:20.656+0000] {subprocess.py:93} INFO - 25/10/19 13:01:20 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-10-19T13:01:20.892+0000] {subprocess.py:93} INFO - 25/10/19 13:01:20 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 2ef039423968, 37865, None)
[2025-10-19T13:01:20.921+0000] {subprocess.py:93} INFO - 25/10/19 13:01:20 INFO BlockManagerMasterEndpoint: Registering block manager 2ef039423968:37865 with 413.9 MiB RAM, BlockManagerId(driver, 2ef039423968, 37865, None)
[2025-10-19T13:01:20.925+0000] {subprocess.py:93} INFO - 25/10/19 13:01:20 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 2ef039423968, 37865, None)
[2025-10-19T13:01:20.928+0000] {subprocess.py:93} INFO - 25/10/19 13:01:20 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 2ef039423968, 37865, None)
[2025-10-19T13:01:30.338+0000] {subprocess.py:93} INFO - Trying to read from: hdfs://192.168.1.10:9000/user/winardi/data/olist/olist_customers_dataset.csv
[2025-10-19T13:01:32.166+0000] {subprocess.py:93} INFO - 25/10/19 13:01:32 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-10-19T13:01:32.236+0000] {subprocess.py:93} INFO - 25/10/19 13:01:32 INFO SharedState: Warehouse path is 'file:/tmp/***tmpr5n83kwn/spark-warehouse'.
[2025-10-19T13:01:53.286+0000] {subprocess.py:93} INFO - 25/10/19 13:01:53 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: hdfs://192.168.1.10:9000/user/winardi/data/olist/olist_customers_dataset.csv.
[2025-10-19T13:01:53.287+0000] {subprocess.py:93} INFO - java.net.ConnectException: Call From 2ef039423968/172.18.0.6 to hadoop:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[2025-10-19T13:01:53.288+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-10-19T13:01:53.289+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-10-19T13:01:53.290+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-10-19T13:01:53.291+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-10-19T13:01:53.292+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-10-19T13:01:53.293+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:913)
[2025-10-19T13:01:53.294+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:828)
[2025-10-19T13:01:53.295+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1616)
[2025-10-19T13:01:53.296+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-10-19T13:01:53.301+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-10-19T13:01:53.303+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-10-19T13:01:53.340+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-10-19T13:01:53.356+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy35.getFileInfo(Unknown Source)
[2025-10-19T13:01:53.357+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:965)
[2025-10-19T13:01:53.364+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-10-19T13:01:53.365+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-10-19T13:01:53.366+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-10-19T13:01:53.367+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-10-19T13:01:53.377+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-10-19T13:01:53.391+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-10-19T13:01:53.415+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-10-19T13:01:53.435+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-10-19T13:01:53.444+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-10-19T13:01:53.459+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy36.getFileInfo(Unknown Source)
[2025-10-19T13:01:53.474+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1739)
[2025-10-19T13:01:53.488+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1753)
[2025-10-19T13:01:53.489+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1750)
[2025-10-19T13:01:53.491+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-10-19T13:01:53.492+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1765)
[2025-10-19T13:01:53.503+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.isDirectory(FileSystem.java:1777)
[2025-10-19T13:01:53.505+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:54)
[2025-10-19T13:01:53.516+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:366)
[2025-10-19T13:01:53.519+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2025-10-19T13:01:53.520+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2025-10-19T13:01:53.521+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-10-19T13:01:53.522+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2025-10-19T13:01:53.524+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:538)
[2025-10-19T13:01:53.527+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-10-19T13:01:53.530+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-10-19T13:01:53.532+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-10-19T13:01:53.533+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-10-19T13:01:53.534+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-10-19T13:01:53.535+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-10-19T13:01:53.536+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-10-19T13:01:53.549+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-10-19T13:01:53.558+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-10-19T13:01:53.560+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-10-19T13:01:53.562+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-10-19T13:01:53.563+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-10-19T13:01:53.564+0000] {subprocess.py:93} INFO - Caused by: java.net.ConnectException: Connection refused
[2025-10-19T13:01:53.565+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2025-10-19T13:01:53.566+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2025-10-19T13:01:53.568+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2025-10-19T13:01:53.570+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:205)
[2025-10-19T13:01:53.573+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:586)
[2025-10-19T13:01:53.580+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:711)
[2025-10-19T13:01:53.582+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:833)
[2025-10-19T13:01:53.583+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:414)
[2025-10-19T13:01:53.594+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1677)
[2025-10-19T13:01:53.599+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1502)
[2025-10-19T13:01:53.600+0000] {subprocess.py:93} INFO - 	... 40 more
[2025-10-19T13:01:55.398+0000] {subprocess.py:93} INFO - ERROR: An error occurred while calling o29.csv.
[2025-10-19T13:01:55.399+0000] {subprocess.py:93} INFO - : java.net.ConnectException: Call From 2ef039423968/172.18.0.6 to hadoop:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[2025-10-19T13:01:55.400+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-10-19T13:01:55.402+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-10-19T13:01:55.403+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-10-19T13:01:55.405+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-10-19T13:01:55.418+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-10-19T13:01:55.419+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:913)
[2025-10-19T13:01:55.421+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:828)
[2025-10-19T13:01:55.423+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1616)
[2025-10-19T13:01:55.424+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-10-19T13:01:55.432+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-10-19T13:01:55.468+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-10-19T13:01:55.471+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-10-19T13:01:55.474+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy35.getFileInfo(Unknown Source)
[2025-10-19T13:01:55.475+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:965)
[2025-10-19T13:01:55.476+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-10-19T13:01:55.485+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-10-19T13:01:55.487+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-10-19T13:01:55.488+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-10-19T13:01:55.490+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-10-19T13:01:55.492+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-10-19T13:01:55.494+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-10-19T13:01:55.495+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-10-19T13:01:55.496+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-10-19T13:01:55.497+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy36.getFileInfo(Unknown Source)
[2025-10-19T13:01:55.500+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1739)
[2025-10-19T13:01:55.501+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1753)
[2025-10-19T13:01:55.501+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1750)
[2025-10-19T13:01:55.502+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-10-19T13:01:55.504+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1765)
[2025-10-19T13:01:55.506+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1760)
[2025-10-19T13:01:55.508+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4(DataSource.scala:756)
[2025-10-19T13:01:55.509+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4$adapted(DataSource.scala:754)
[2025-10-19T13:01:55.510+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:384)
[2025-10-19T13:01:55.511+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-10-19T13:01:55.512+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-10-19T13:01:55.515+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-10-19T13:01:55.516+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-10-19T13:01:55.568+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-10-19T13:01:55.569+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-10-19T13:01:55.569+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-10-19T13:01:55.570+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[2025-10-19T13:01:55.572+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[2025-10-19T13:01:55.577+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[2025-10-19T13:01:55.577+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[2025-10-19T13:01:55.581+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[2025-10-19T13:01:55.582+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[2025-10-19T13:01:55.583+0000] {subprocess.py:93} INFO - Caused by: java.net.ConnectException: Connection refused
[2025-10-19T13:01:55.584+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2025-10-19T13:01:55.585+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2025-10-19T13:01:55.586+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2025-10-19T13:01:55.587+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:205)
[2025-10-19T13:01:55.587+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:586)
[2025-10-19T13:01:55.588+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:711)
[2025-10-19T13:01:55.588+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:833)
[2025-10-19T13:01:55.589+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:414)
[2025-10-19T13:01:55.591+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1677)
[2025-10-19T13:01:55.592+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1502)
[2025-10-19T13:01:55.593+0000] {subprocess.py:93} INFO - 	... 37 more
[2025-10-19T13:01:55.593+0000] {subprocess.py:93} INFO - 
[2025-10-19T13:01:55.594+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-19T13:01:55.594+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/hdfs_spark_test.py", line 20, in main
[2025-10-19T13:01:55.595+0000] {subprocess.py:93} INFO -     df = spark.read.csv(hdfs_path, header=True, inferSchema=True)
[2025-10-19T13:01:55.596+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 740, in csv
[2025-10-19T13:01:55.596+0000] {subprocess.py:93} INFO -     return self._df(self._jreader.csv(self._spark._sc._jvm.PythonUtils.toSeq(path)))
[2025-10-19T13:01:55.597+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-10-19T13:01:55.597+0000] {subprocess.py:93} INFO -     return_value = get_return_value(
[2025-10-19T13:01:55.598+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-10-19T13:01:55.599+0000] {subprocess.py:93} INFO -     return f(*a, **kw)
[2025-10-19T13:01:55.600+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-10-19T13:01:55.601+0000] {subprocess.py:93} INFO -     raise Py4JJavaError(
[2025-10-19T13:01:55.602+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o29.csv.
[2025-10-19T13:01:55.602+0000] {subprocess.py:93} INFO - : java.net.ConnectException: Call From 2ef039423968/172.18.0.6 to hadoop:9000 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
[2025-10-19T13:01:55.603+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[2025-10-19T13:01:55.605+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[2025-10-19T13:01:55.607+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[2025-10-19T13:01:55.608+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
[2025-10-19T13:01:55.668+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
[2025-10-19T13:01:55.671+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:913)
[2025-10-19T13:01:55.677+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:828)
[2025-10-19T13:01:55.680+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getRpcResponse(Client.java:1616)
[2025-10-19T13:01:55.685+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1558)
[2025-10-19T13:01:55.691+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1455)
[2025-10-19T13:01:55.693+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:242)
[2025-10-19T13:01:55.695+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.ProtobufRpcEngine2$Invoker.invoke(ProtobufRpcEngine2.java:129)
[2025-10-19T13:01:55.699+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy35.getFileInfo(Unknown Source)
[2025-10-19T13:01:55.701+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:965)
[2025-10-19T13:01:55.703+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-10-19T13:01:55.704+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-10-19T13:01:55.705+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-10-19T13:01:55.706+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-10-19T13:01:55.708+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:422)
[2025-10-19T13:01:55.709+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeMethod(RetryInvocationHandler.java:165)
[2025-10-19T13:01:55.709+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invoke(RetryInvocationHandler.java:157)
[2025-10-19T13:01:55.711+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler$Call.invokeOnce(RetryInvocationHandler.java:95)
[2025-10-19T13:01:55.714+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:359)
[2025-10-19T13:01:55.768+0000] {subprocess.py:93} INFO - 	at jdk.proxy2/jdk.proxy2.$Proxy36.getFileInfo(Unknown Source)
[2025-10-19T13:01:55.771+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1739)
[2025-10-19T13:01:55.773+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1753)
[2025-10-19T13:01:55.775+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1750)
[2025-10-19T13:01:55.777+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
[2025-10-19T13:01:55.778+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1765)
[2025-10-19T13:01:55.782+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.exists(FileSystem.java:1760)
[2025-10-19T13:01:55.782+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4(DataSource.scala:756)
[2025-10-19T13:01:55.783+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$4$adapted(DataSource.scala:754)
[2025-10-19T13:01:55.784+0000] {subprocess.py:93} INFO - 	at org.apache.spark.util.ThreadUtils$.$anonfun$parmap$2(ThreadUtils.scala:384)
[2025-10-19T13:01:55.785+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[2025-10-19T13:01:55.786+0000] {subprocess.py:93} INFO - 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[2025-10-19T13:01:55.788+0000] {subprocess.py:93} INFO - 	at scala.util.Success.map(Try.scala:213)
[2025-10-19T13:01:55.789+0000] {subprocess.py:93} INFO - 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[2025-10-19T13:01:55.790+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[2025-10-19T13:01:55.791+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[2025-10-19T13:01:55.792+0000] {subprocess.py:93} INFO - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[2025-10-19T13:01:55.793+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
[2025-10-19T13:01:55.794+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[2025-10-19T13:01:55.795+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[2025-10-19T13:01:55.796+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[2025-10-19T13:01:55.799+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[2025-10-19T13:01:55.800+0000] {subprocess.py:93} INFO - 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
[2025-10-19T13:01:55.801+0000] {subprocess.py:93} INFO - Caused by: java.net.ConnectException: Connection refused
[2025-10-19T13:01:55.807+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2025-10-19T13:01:55.915+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2025-10-19T13:01:55.920+0000] {subprocess.py:93} INFO - 	at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2025-10-19T13:01:55.928+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:205)
[2025-10-19T13:01:55.932+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:586)
[2025-10-19T13:01:55.934+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:711)
[2025-10-19T13:01:55.937+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:833)
[2025-10-19T13:01:55.939+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client$Connection.access$3800(Client.java:414)
[2025-10-19T13:01:55.942+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.getConnection(Client.java:1677)
[2025-10-19T13:01:55.945+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.ipc.Client.call(Client.java:1502)
[2025-10-19T13:01:55.968+0000] {subprocess.py:93} INFO - 	... 37 more
[2025-10-19T13:01:55.971+0000] {subprocess.py:93} INFO - 
[2025-10-19T13:01:55.987+0000] {subprocess.py:93} INFO - 25/10/19 13:01:55 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-10-19T13:01:56.071+0000] {subprocess.py:93} INFO - 25/10/19 13:01:55 INFO SparkUI: Stopped Spark web UI at http://2ef039423968:4040
[2025-10-19T13:01:56.080+0000] {subprocess.py:93} INFO - 25/10/19 13:01:55 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-10-19T13:01:56.081+0000] {subprocess.py:93} INFO - 25/10/19 13:01:55 INFO MemoryStore: MemoryStore cleared
[2025-10-19T13:01:56.097+0000] {subprocess.py:93} INFO - 25/10/19 13:01:55 INFO BlockManager: BlockManager stopped
[2025-10-19T13:01:56.102+0000] {subprocess.py:93} INFO - 25/10/19 13:01:55 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-10-19T13:01:56.169+0000] {subprocess.py:93} INFO - 25/10/19 13:01:55 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-10-19T13:01:56.171+0000] {subprocess.py:93} INFO - 25/10/19 13:01:55 INFO SparkContext: Successfully stopped SparkContext
[2025-10-19T13:01:56.207+0000] {subprocess.py:93} INFO - 25/10/19 13:01:56 INFO ShutdownHookManager: Shutdown hook called
[2025-10-19T13:01:56.269+0000] {subprocess.py:93} INFO - 25/10/19 13:01:56 INFO ShutdownHookManager: Deleting directory /tmp/spark-eebaacb8-8843-40a5-a205-cce85e845612/pyspark-ce9fd94b-df8c-4da8-b975-cf623e9d1907
[2025-10-19T13:01:56.275+0000] {subprocess.py:93} INFO - 25/10/19 13:01:56 INFO ShutdownHookManager: Deleting directory /tmp/spark-eebaacb8-8843-40a5-a205-cce85e845612
[2025-10-19T13:01:56.288+0000] {subprocess.py:93} INFO - 25/10/19 13:01:56 INFO ShutdownHookManager: Deleting directory /tmp/spark-f6400835-bed5-47bc-a043-1042c1ee3074
[2025-10-19T13:01:56.408+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-19T13:01:56.437+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-19T13:01:56.453+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=test_hdfs_spark_bash, task_id=run_spark_local, execution_date=20251019T130018, start_date=20251019T130027, end_date=20251019T130156
[2025-10-19T13:01:56.508+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 143 for task run_spark_local (Bash command failed. The command returned a non-zero exit code 1.; 502)
[2025-10-19T13:01:56.534+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-10-19T13:01:56.569+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
